import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      // General
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'submit': 'Submit',
      'next': 'Next',
      'cancel': 'Cancel',
      'error': 'Error',
      'success': 'Success',
      'pending': 'Pending',
      'approve': 'Approve',
      'reject': 'Reject',
      'approved': 'Approved',
      'disapprove': 'Disapprove',
      'issued': 'Issued',
      'all': 'All',
      'date': 'Date',
      'name': 'Name',
      'status': 'Status',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',

      // HomePage
      'search_hint_admin': 'Admin here...',
      'search_hint_staff': 'Staff here...',
      'search_hint_asnaf': 'Asnaf here...',
      'upcoming_activities': 'Upcoming Activities',
      'get_points': 'Get @points pts',
      'no_location': 'No location',
      'search_page': 'Search Page',
      'shopping_page': 'Shopping Page',
      'inbox_page': 'Inbox Page',
      'profile_page': 'Profile Page',

      // LoginPage
      'login_title': 'Sign up or log in',
      'login_subtitle': 'Select your preferred method to continue',
      'login_google': 'Continue with Google',
      'login_email': 'Continue with Email',
      'login_not_implemented': 'Email sign-in not implemented yet.',
      'login_failed': 'Google sign-in canceled or failed.',
      'login_error': 'Google sign-in error: @error',

      // AmountPage
      'help_asnaf_by_amount': 'Help Asnaf by Amount',
      'other': 'Other',
      'donor_info': 'Donor’s information',
      'tax_exemption_q': 'Would you like a tax exemption letter to be sent to you?',
      'designation': 'Designation',
      'select': 'Select',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter full name',
      'email': 'Email',
      'enter_email': 'Enter email',
      'contact_number': 'Contact Number',
      'enter_mobile_number': 'Enter mobile number',
      'payment_method': 'Payment Method',
      'card': 'Card',
      'fpx': 'FPX',
      'donate_now': 'Donate Now',
      'fix_errors_prompt': 'Please fix the errors before submitting.',
      'select_amount_prompt': 'Please select or enter an amount.',
      'valid_amount_prompt': 'Please enter a valid amount.',
      'donation_processing': 'Donation processing... Please follow payment instructions.',
      'full_name_required': 'Full name is required',
      'email_required': 'Email is required',
      'valid_email_prompt': 'Enter a valid email address',
      'contact_required': 'Contact number is required',
      'contact_must_be_digits': 'Must be 9-10 digits',
      'amount_must_be_number': 'Please enter a number',
      'amount_gt_one': 'Amount must be greater than RM1',

      // ApplicationReviewScreen
      'app_under_review': 'Your application is under review!',
      'app_review_notify': 'We\'re currently reviewing your application.\nWe\'ll notify your result within 6-7 business days.',

      // ApplicationsScreen
      'your_app_status': 'Your Application Status',
      'track_app_submitted': 'Track applications you’ve submitted.',
      'search_code': 'Search Code',
      'no_applications_found': 'No applications found',
      'submitted': 'Submitted',
      'completed': 'Completed',
      'rewards': 'Rewards',

      "dashboard_verify_applications": "Verify Applications",
      "dashboard_issue_reward": "Issue Reward",
      "dashboard_view_reports": "View Reports",
      "dashboard_manage_user": "Manage User",
      "dashboard_help_asnaf": "Help Asnaf",
      "dashboard_apply_aid": "Apply Aid",
      "dashboard_application_status": "Application Status",
      "dashboard_redeem_rewards": "Redeem Rewards",
      "dashboard_submit_application": "Submit Application",
      "dashboard_asnaf_vouchers": "Asnaf Vouchers",
      "dashboard_monitor_applications": "Monitor Applications",
      "dashboard_manage_events": "Manage Events",
      "userpoints_points": "Points",
      "userpoints_pickup_item": "Pickup Item",
      "userpoints_checkin_event": "Check-In Event",
      "userpoints_help_attendance": "Help Attendance",
      "userpoints_checkin_description": "Earn points by confirming\nyour attendance",

  "login_title": "Sign up or log in",
  "login_subtitle": "Select your preferred method to continue",
  "login_google": "Continue with Google",
  "login_email": "Continue with Email",
  "login_failed": "Google sign-in canceled or failed.",
  "login_error": "Google sign-in error: @error",
  "login_not_implemented": "Email sign-in not implemented yet.",
  "profile_set_name_hint": "Set your name",
  "profile_change_photo": "Change profile photo",
  "profile_no_email": "No Email Available",
  "profile_set_username": "Set username",
  "profile_mobile_number": "Mobile Number",
  "profile_nric": "NRIC",
  "profile_home_address": "Home Address",
  "profile_city": "City",
  "profile_postcode": "Postcode",
  "profile_logout": "Logout",
  "profile_login": "Login",

      "help_asnaf_by": "Help Asnaf By...",
      "help_asnaf_amount": "Amount",
      "help_asnaf_amount_desc": "You can contribute any amount you wish. Every contribution, no matter how small, makes a difference.",
      "help_asnaf_package": "Package",
      "help_asnaf_package_desc": "Choose from a list of pre-set package vouchers that you’re willing to sponsor. These packages provide essential items to Asnaf.",
      "help_asnaf_item_bank": "Food/Item Bank",
      "help_asnaf_item_bank_desc": "Donate any food or item you have to MADAD centre. It will be distributed to Asnaf.",
      "package_page_title": "Help Asnaf by Package",
      "package_no_packages": "No package available",
      "package_choice": "Choice",
      "package_quantity": "Quantity",
      "package_value": "Value (RM)",
      "package_total": "Total:",
      "package_overall_amount": "Overall Amount (RM):",
      "pay_package_title": "Help Asnaf by Package (@count selected)",
      "pay_package_unnamed_hamper": "Unnamed Hamper",
      "pay_package_config_error": "Payment configuration error. Please contact support.",
      "pay_package_initiation_error": "Payment initiation error. Please try again.",
      "pay_package_failed_initiation": "Failed to initiate payment.",
      "pay_package_could_not_open": "Could not open payment page.",
      "pay_package_processing": "Donation processing... Please follow payment instructions.",

      "food_item_bank_title": "Food / Item Bank",
      "food_item_bank_submit_success": "Submitted successfully!",
      "food_item_bank_submit_error": "Error: @error",
      "food_item_bank_required_field": "Required",
      "food_item_bank_type": "Type",
      "food_item_bank_type_food": "Food",
      "food_item_bank_type_item": "Item",
      "food_item_bank_item_name_label": "Item Name",
      "food_item_bank_item_name_hint": "Enter item name",
      "food_item_bank_item_type_label": "Type of Item",
      "food_item_bank_item_type_clothes": "Clothes",
      "food_item_bank_item_type_accessory": "Accessory",
      "food_item_bank_item_type_baby": "Baby Stuff",
      "food_item_bank_item_type_school": "School Stuff",
      "food_item_bank_item_type_other": "Other",
      "food_item_bank_number_of_items": "Number of Items",
      "food_item_bank_condition_new": "New",
      "food_item_bank_condition_used": "Used",
      "food_item_bank_estimated_value": "Estimated Value (RM)",
      "food_item_bank_giver_name_label": "Giver Name",
      "food_item_bank_giver_name_hint": "Enter your name",
      "food_item_bank_phone_label": "Phone Number",
      "food_item_bank_phone_hint": "Enter your phone number",
      "food_item_bank_email_label": "Email",
      "food_item_bank_email_hint": "Enter your email",
      "food_item_bank_tax_question": "Would you like a tax-exemption letter?",
      "food_item_bank_picture_label": "Picture of Food/Item",
      "food_item_bank_upload_tap": "Tap to upload image",
      "food_item_bank_upload_format": "Format: jpeg/jpg/png",

      "bottom_nav_login_prompt": "Please log in to view your profile.",
      "bottom_nav_home": "Home",
      "bottom_nav_track_order": "Track order",
      "bottom_nav_order": "Order",
      "bottom_nav_stock": "Stock",
      "bottom_nav_shopping": "Shopping",
      "bottom_nav_inbox": "Inbox",
      "bottom_nav_profile": "Profile",

    },
    'ms': {
      // General
      'ok': 'OK',
      'yes': 'Ya',
      'no': 'Tidak',
      'submit': 'Hantar',
      'next': 'Seterusnya',
      'cancel': 'Batal',
      'error': 'Ralat',
      'success': 'Berjaya',
      'pending': 'Menunggu',
      'approve': 'Lulus',
      'reject': 'Tolak',
      'approved': 'Diluluskan',
      'disapprove': 'Tidak Lulus',
      'issued': 'Dikeluarkan',
      'all': 'Semua',
      'date': 'Tarikh',
      'name': 'Nama',
      'status': 'Status',
      'search': 'Cari',
      'filter': 'Tapis',
      'sort': 'Susun',

      // HomePage
      'search_hint_admin': 'Admin di sini...',
      'search_hint_staff': 'Staf di sini...',
      'search_hint_asnaf': 'Asnaf di sini...',
      'upcoming_activities': 'Aktiviti Akan Datang',
      'get_points': 'Dapat @points mata',
      'no_location': 'Tiada lokasi',
      'search_page': 'Halaman Carian',
      'shopping_page': 'Halaman Membeli-belah',
      'inbox_page': 'Halaman Peti Masuk',
      'profile_page': 'Halaman Profil',

      // LoginPage
      'login_title': 'Daftar atau log masuk',
      'login_subtitle': 'Pilih kaedah pilihan anda untuk meneruskan',
      'login_google': 'Teruskan dengan Google',
      'login_email': 'Teruskan dengan E-mel',
      'login_not_implemented': 'Log masuk e-mel belum dilaksanakan.',
      'login_failed': 'Log masuk Google dibatalkan atau gagal.',
      'login_error': 'Ralat log masuk Google: @error',

      // AmountPage
      'help_asnaf_by_amount': 'Bantu Asnaf melalui Jumlah',
      'other': 'Lain-lain',
      'donor_info': 'Maklumat Penderma',
      'tax_exemption_q': 'Adakah anda mahu surat pengecualian cukai dihantar kepada anda?',
      'designation': 'Jawatan',
      'select': 'Pilih',
      'full_name': 'Nama Penuh',
      'enter_full_name': 'Masukkan nama penuh',
      'email': 'E-mel',
      'enter_email': 'Masukkan e-mel',
      'contact_number': 'Nombor Hubungan',
      'enter_mobile_number': 'Masukkan nombor telefon bimbit',
      'payment_method': 'Kaedah Pembayaran',
      'card': 'Kad',
      'fpx': 'FPX',
      'donate_now': 'Derma Sekarang',
      'fix_errors_prompt': 'Sila betulkan ralat sebelum menghantar.',
      'select_amount_prompt': 'Sila pilih atau masukkan jumlah.',
      'valid_amount_prompt': 'Sila masukkan jumlah yang sah.',
      'donation_processing': 'Memproses derma... Sila ikut arahan pembayaran.',
      'full_name_required': 'Nama penuh diperlukan',
      'email_required': 'E-mel diperlukan',
      'valid_email_prompt': 'Masukkan alamat e-mel yang sah',
      'contact_required': 'Nombor hubungan diperlukan',
      'contact_must_be_digits': 'Mestilah 9-10 digit',
      'amount_must_be_number': 'Sila masukkan nombor',
      'amount_gt_one': 'Jumlah mesti lebih besar daripada RM1',

      // ApplicationReviewScreen
      'app_under_review': 'Permohonan anda sedang disemak!',
      'app_review_notify': 'Kami sedang menyemak permohonan anda.\nKami akan memberitahu keputusan anda dalam 6-7 hari perniagaan.',

      // ApplicationsScreen
      'your_app_status': 'Status Permohonan Anda',
      'track_app_submitted': 'Jejaki permohonan yang telah anda hantar.',
      'search_code': 'Cari Kod',
      'no_applications_found': 'Tiada permohonan ditemui',
      'submitted': 'Dihantar',
      'completed': 'Selesai',
      'rewards': 'Ganjaran',

      "dashboard_verify_applications": "Sahkan Permohonan",
      "dashboard_issue_reward": "Keluarkan Ganjaran",
      "dashboard_view_reports": "Lihat Laporan",
      "dashboard_manage_user": "Urus Pengguna",
      "dashboard_help_asnaf": "Bantu Asnaf",
      "dashboard_apply_aid": "Mohon Bantuan",
      "dashboard_application_status": "Status Permohonan",
      "dashboard_redeem_rewards": "Tebus Ganjaran",
      "dashboard_submit_application": "Hantar Permohonan",
      "dashboard_asnaf_vouchers": "Baucar Asnaf",
      "dashboard_monitor_applications": "Pantau Permohonan",
      "dashboard_manage_events": "Urus Acara",
      "userpoints_points": "Mata",
      "userpoints_pickup_item": "Ambil Barangan",
      "userpoints_checkin_event": "Daftar Masuk Acara",
      "userpoints_help_attendance": "Bantu Kehadiran",
      "userpoints_checkin_description": "Dapatkan mata dengan mengesahkan\nkehadiran anda",

      "login_title": "Daftar atau log masuk",
      "login_subtitle": "Pilih kaedah pilihan anda untuk meneruskan",
      "login_google": "Teruskan dengan Google",
      "login_email": "Teruskan dengan E-mel",
      "login_failed": "Log masuk Google dibatalkan atau gagal.",
      "login_error": "Ralat log masuk Google: @error",
      "login_not_implemented": "Log masuk e-mel belum dilaksanakan.",
      "profile_set_name_hint": "Tetapkan nama anda",
      "profile_change_photo": "Tukar gambar profil",
      "profile_no_email": "Tiada E-mel Tersedia",
      "profile_set_username": "Tetapkan nama pengguna",
      "profile_mobile_number": "Nombor Telefon Bimbit",
      "profile_nric": "NRIC",
      "profile_home_address": "Alamat Rumah",
      "profile_city": "Bandar",
      "profile_postcode": "Poskod",
      "profile_logout": "Log keluar",
      "profile_login": "Log masuk",

      "help_asnaf_by": "Bantu Asnaf Melalui...",
      "help_asnaf_amount": "Jumlah",
      "help_asnaf_amount_desc": "Anda boleh menyumbang sebarang jumlah yang anda inginkan. Setiap sumbangan, tidak kira sekecil mana, akan membawa perubahan.",
      "help_asnaf_package": "Pakej",
      "help_asnaf_package_desc": "Pilih daripada senarai baucar pakej pra-tetap yang anda sanggup taja. Pakej-pakej ini menyediakan barangan keperluan kepada Asnaf.",
      "help_asnaf_item_bank": "Bank Makanan/Barangan",
      "help_asnaf_item_bank_desc": "Sumbangkan sebarang makanan atau barangan yang anda ada ke pusat MADAD. Ia akan diagihkan kepada Asnaf.",
      "package_page_title": "Bantu Asnaf melalui Pakej",
      "package_no_packages": "Tiada pakej tersedia",
      "package_choice": "Pilihan",
      "package_quantity": "Kuantiti",
      "package_value": "Nilai (RM)",
      "package_total": "Jumlah:",
      "package_overall_amount": "Jumlah Keseluruhan (RM):",
      "pay_package_title": "Bantu Asnaf melalui Pakej (@count dipilih)",
      "pay_package_unnamed_hamper": "Hamper Tanpa Nama",
      "pay_package_config_error": "Ralat konfigurasi pembayaran. Sila hubungi sokongan.",
      "pay_package_initiation_error": "Ralat permulaan pembayaran. Sila cuba lagi.",
      "pay_package_failed_initiation": "Gagal untuk memulakan pembayaran.",
      "pay_package_could_not_open": "Tidak dapat membuka halaman pembayaran.",
      "pay_package_processing": "Memproses derma... Sila ikut arahan pembayaran.",

      "food_item_bank_title": "Bank Makanan / Barangan",
      "food_item_bank_submit_success": "Berjaya dihantar!",
      "food_item_bank_submit_error": "Ralat: @error",
      "food_item_bank_required_field": "Diperlukan",
      "food_item_bank_type": "Jenis",
      "food_item_bank_type_food": "Makanan",
      "food_item_bank_type_item": "Barangan",
      "food_item_bank_item_name_label": "Nama Barangan",
      "food_item_bank_item_name_hint": "Masukkan nama barangan",
      "food_item_bank_item_type_label": "Jenis Barangan",
      "food_item_bank_item_type_clothes": "Pakaian",
      "food_item_bank_item_type_accessory": "Aksesori",
      "food_item_bank_item_type_baby": "Barangan Bayi",
      "food_item_bank_item_type_school": "Barangan Sekolah",
      "food_item_bank_item_type_other": "Lain-lain",
      "food_item_bank_number_of_items": "Bilangan Barangan",
      "food_item_bank_condition_new": "Baru",
      "food_item_bank_condition_used": "Terpakai",
      "food_item_bank_estimated_value": "Anggaran Nilai (RM)",
      "food_item_bank_giver_name_label": "Nama Pemberi",
      "food_item_bank_giver_name_hint": "Masukkan nama anda",
      "food_item_bank_phone_label": "Nombor Telefon",
      "food_item_bank_phone_hint": "Masukkan nombor telefon anda",
      "food_item_bank_email_label": "E-mel",
      "food_item_bank_email_hint": "Masukkan e-mel anda",
      "food_item_bank_tax_question": "Adakah anda mahukan surat pengecualian cukai?",
      "food_item_bank_picture_label": "Gambar Makanan/Barangan",
      "food_item_bank_upload_tap": "Ketik untuk muat naik imej",
      "food_item_bank_upload_format": "Format: jpeg/jpg/png",

      "bottom_nav_login_prompt": "Sila log masuk untuk melihat profil anda.",
      "bottom_nav_home": "Utama",
      "bottom_nav_track_order": "Jejak Pesanan",
      "bottom_nav_order": "Pesanan",
      "bottom_nav_stock": "Stok",
      "bottom_nav_shopping": "Membeli-belah",
      "bottom_nav_inbox": "Peti Masuk",
      "bottom_nav_profile": "Profil",
    },
  };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]![key] ?? key;
  }

  String translateWithArgs(String key, Map<String, String> args) {
    String translation = _localizedStrings[locale.languageCode]![key] ?? key;
    args.forEach((key, value) {
      translation = translation.replaceAll('@$key', value);
    });
    return translation;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ms'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}