import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      // General
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'submit': 'Submit',
      'next': 'Next',
      'cancel': 'Cancel',
      'error': 'Error',
      'success': 'Success',
      'pending': 'Pending',
      'approve': 'Approve',
      'reject': 'Reject',
      'approved': 'Approved',
      'disapprove': 'Disapprove',
      'issued': 'Issued',
      'all': 'All',
      'date': 'Date',
      'name': 'Name',
      'status': 'Status',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',

      // HomePage
      'search_hint_admin': 'Admin here...',
      'search_hint_staff': 'Staff here...',
      'search_hint_asnaf': 'Asnaf here...',
      'upcoming_activities': 'Upcoming Activities',
      'get_points': 'Get @points pts',
      'no_location': 'No location',
      'search_page': 'Search Page',
      'shopping_page': 'Shopping Page',
      'inbox_page': 'Inbox Page',
      'profile_page': 'Profile Page',

      // LoginPage
      'login_title': 'Sign up or log in',
      'login_subtitle': 'Select your preferred method to continue',
      'login_google': 'Continue with Google',
      'login_email': 'Continue with Email',
      'login_not_implemented': 'Email sign-in not implemented yet.',
      'login_failed': 'Google sign-in canceled or failed.',
      'login_error': 'Google sign-in error: @error',

      // AmountPage
      'help_asnaf_by_amount': 'Help Asnaf by Amount',
      'other': 'Other',
      'donor_info': 'Donor’s information',
      'tax_exemption_q': 'Would you like a tax exemption letter to be sent to you?',
      'designation': 'Designation',
      'select': 'Select',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter full name',
      'email': 'Email',
      'enter_email': 'Enter email',
      'contact_number': 'Contact Number',
      'enter_mobile_number': 'Enter mobile number',
      'payment_method': 'Payment Method',
      'card': 'Card',
      'fpx': 'FPX',
      'donate_now': 'Donate Now',
      'fix_errors_prompt': 'Please fix the errors before submitting.',
      'select_amount_prompt': 'Please select or enter an amount.',
      'valid_amount_prompt': 'Please enter a valid amount.',
      'donation_processing': 'Donation processing... Please follow payment instructions.',
      'full_name_required': 'Full name is required',
      'email_required': 'Email is required',
      'valid_email_prompt': 'Enter a valid email address',
      'contact_required': 'Contact number is required',
      'contact_must_be_digits': 'Must be 9-10 digits',
      'amount_must_be_number': 'Please enter a number',
      'amount_gt_one': 'Amount must be greater than RM1',

      // ApplicationReviewScreen
      'app_under_review': 'Your application is under review!',
      'app_review_notify': 'We\'re currently reviewing your application.\nWe\'ll notify your result within 6-7 business days.',

      // ApplicationsScreen
      'your_app_status': 'Your Application Status',
      'track_app_submitted': 'Track applications you’ve submitted.',
      'search_code': 'Search Code',
      'no_applications_found': 'No applications found',
      'submitted': 'Submitted',
      'completed': 'Completed',
      'rewards': 'Rewards',

      "dashboard_verify_applications": "Verify Applications",
      "dashboard_issue_reward": "Issue Reward",
      "dashboard_view_reports": "View Reports",
      "dashboard_manage_user": "Manage User",
      "dashboard_help_asnaf": "Help Asnaf",
      "dashboard_apply_aid": "Apply Aid",
      "dashboard_application_status": "Application Status",
      "dashboard_redeem_rewards": "Redeem Rewards",
      "dashboard_submit_application": "Submit Application",
      "dashboard_asnaf_vouchers": "Asnaf Vouchers",
      "dashboard_monitor_applications": "Monitor Applications",
      "dashboard_manage_events": "Manage Events",
      "userpoints_points": "Points",
      "userpoints_pickup_item": "Pickup Item",
      "userpoints_checkin_event": "Check-In Event",
      "userpoints_help_attendance": "Help Attendance",
      "userpoints_checkin_description": "Earn points by confirming\nyour attendance",

  "login_title": "Sign up or log in",
  "login_subtitle": "Select your preferred method to continue",
  "login_google": "Continue with Google",
  "login_email": "Continue with Email",
  "login_failed": "Google sign-in canceled or failed.",
  "login_error": "Google sign-in error: @error",
  "login_not_implemented": "Email sign-in not implemented yet.",
  "profile_set_name_hint": "Set your name",
  "profile_change_photo": "Change profile photo",
  "profile_no_email": "No Email Available",
  "profile_set_username": "Set username",
  "profile_mobile_number": "Mobile Number",
  "profile_nric": "NRIC",
  "profile_home_address": "Home Address",
  "profile_city": "City",
  "profile_postcode": "Postcode",
  "profile_logout": "Logout",
  "profile_login": "Login",

      "help_asnaf_by": "Help Asnaf By...",
      "help_asnaf_amount": "Amount",
      "help_asnaf_amount_desc": "You can contribute any amount you wish. Every contribution, no matter how small, makes a difference.",
      "help_asnaf_package": "Package",
      "help_asnaf_package_desc": "Choose from a list of pre-set package vouchers that you’re willing to sponsor. These packages provide essential items to Asnaf.",
      "help_asnaf_item_bank": "Food/Item Bank",
      "help_asnaf_item_bank_desc": "Donate any food or item you have to MADAD centre. It will be distributed to Asnaf.",
      "package_page_title": "Help Asnaf by Package",
      "package_no_packages": "No package available",
      "package_choice": "Choice",
      "package_quantity": "Quantity",
      "package_value": "Value (RM)",
      "package_total": "Total:",
      "package_overall_amount": "Overall Amount (RM):",
      "pay_package_title": "Help Asnaf by Package (@count selected)",
      "pay_package_unnamed_hamper": "Unnamed Hamper",
      "pay_package_config_error": "Payment configuration error. Please contact support.",
      "pay_package_initiation_error": "Payment initiation error. Please try again.",
      "pay_package_failed_initiation": "Failed to initiate payment.",
      "pay_package_could_not_open": "Could not open payment page.",
      "pay_package_processing": "Donation processing... Please follow payment instructions.",

      "food_item_bank_title": "Food / Item Bank",
      "food_item_bank_submit_success": "Submitted successfully!",
      "food_item_bank_submit_error": "Error: @error",
      "food_item_bank_required_field": "Required",
      "food_item_bank_type": "Type",
      "food_item_bank_type_food": "Food",
      "food_item_bank_type_item": "Item",
      "food_item_bank_item_name_label": "Item Name",
      "food_item_bank_item_name_hint": "Enter item name",
      "food_item_bank_item_type_label": "Type of Item",
      "food_item_bank_item_type_clothes": "Clothes",
      "food_item_bank_item_type_accessory": "Accessory",
      "food_item_bank_item_type_baby": "Baby Stuff",
      "food_item_bank_item_type_school": "School Stuff",
      "food_item_bank_item_type_other": "Other",
      "food_item_bank_number_of_items": "Number of Items",
      "food_item_bank_condition_new": "New",
      "food_item_bank_condition_used": "Used",
      "food_item_bank_estimated_value": "Estimated Value (RM)",
      "food_item_bank_giver_name_label": "Giver Name",
      "food_item_bank_giver_name_hint": "Enter your name",
      "food_item_bank_phone_label": "Phone Number",
      "food_item_bank_phone_hint": "Enter your phone number",
      "food_item_bank_email_label": "Email",
      "food_item_bank_email_hint": "Enter your email",
      "food_item_bank_tax_question": "Would you like a tax-exemption letter?",
      "food_item_bank_picture_label": "Picture of Food/Item",
      "food_item_bank_upload_tap": "Tap to upload image",
      "food_item_bank_upload_format": "Format: jpeg/jpg/png",

      "bottom_nav_login_prompt": "Please log in to view your profile.",
      "bottom_nav_home": "Home",
      "bottom_nav_track_order": "Track order",
      "bottom_nav_order": "Order",
      "bottom_nav_stock": "Stock",
      "bottom_nav_shopping": "Shopping",
      "bottom_nav_inbox": "Inbox",
      "bottom_nav_profile": "Profile",

      "ok": "OK",
      "next": "Next",
      "submit": "Submit",
      "yes": "Yes",
      "no": "No",

      "app_review_title": "Your application is under review!",
      "app_review_subtitle": "We're currently reviewing your application.\nWe'll notify your result within 6-7 business days.",

      "ekyc_title": "eKYC Verification",
      "ekyc_error_missing_images": "Please capture both NRIC and Selfie images.",
      "ekyc_error_nric_validation_failed": "NRIC validation failed. Please ensure the photo is clear, includes a face, and has readable text with a valid NRIC number and name.",
      "ekyc_error_selfie_validation_failed": "Selfie validation failed. Please ensure your face is clearly visible in the selfie.",
      "ekyc_error_generic": "An error occurred during eKYC process: @error",
      "ekyc_validation_error_title": "Validation Error",
      "ekyc_capture_nric_title": "1. Capture NRIC Photo",
      "ekyc_capture_selfie_title": "2. Take a Selfie",
      "ekyc_verify_submit_button": "Verify & Submit",
      "ekyc_tap_to_open_camera": "Tap to open camera",

      "apply_aid_submit_success": "Application submitted successfully!",
      "apply_aid_submit_fail": "Failed to submit application. Please try again.",
      "apply_aid_ekyc_success": "eKYC Verification Successful!",
      "apply_aid_validation_mobile": "Please enter a valid Malaysian mobile number.",
      "apply_aid_validation_addr1": "Please enter Address Line 1.",
      "apply_aid_validation_postcode": "Please enter a valid 5-digit postcode.",
      "apply_aid_validation_city_state": "City and State should be auto-populated from a valid postcode.",
      "apply_aid_validation_residency": "Please select your residency status.",
      "apply_aid_validation_employment": "Please select your employment status.",
      "apply_aid_validation_occupation": "Please enter your occupation.",
      "apply_aid_validation_income": "Please enter your monthly income.",
      "apply_aid_validation_income_numeric": "Please enter a valid number for monthly income.",
      "apply_aid_validation_income_limit": "Monthly income cannot exceed RM 8,000 to be eligible for aid.",
      "apply_aid_validation_is_asnaf": "Please specify if you are an Asnaf.",
      "apply_aid_validation_asnaf_in": "Please specify where you are registered as an Asnaf.",
      "apply_aid_validation_justification": "Please provide a justification for your application.",
      "apply_aid_validation_ekyc_incomplete": "Please complete eKYC verification first.",
      "apply_aid_validation_proof_address": "Please upload your Proof of Address.",
      "apply_aid_validation_proof_income": "Please upload your Proof of Income.",
      "apply_aid_validation_all_fields": "Please ensure all fields are filled correctly before submitting.",
      "apply_aid_step1_title": "Share your personal details",
      "apply_aid_step1_subtitle": "Fill in your personal details to begin your application",
      "apply_aid_step2_title": "Check your eligibility",
      "apply_aid_step2_subtitle": "Answer a few simple questions to see if you meet our eligibility criteria",
      "apply_aid_step3_title": "Upload required documents",
      "apply_aid_step3_subtitle": "We need to verify your identity and financial status. Please upload the required documents",
      "apply_aid_step4_title": "Review your documents",
      "apply_aid_step4_subtitle": "Please check the uploaded documents before submitting.",
      "apply_aid_step5_title": "Kita Tongtong Agreement",
      "apply_aid_step5_subtitle": "Please read and agree to the terms and conditions before submitting your application.",
      "apply_aid_label_email": "Email",
      "apply_aid_hint_email": "Your email address",
      "apply_aid_label_mobile": "Mobile Number",
      "apply_aid_hint_mobile": "123456789",
      "apply_aid_label_addr1": "Address Line 1",
      "apply_aid_hint_addr1": "e.g., Lot 123, Jalan Merdeka",
      "apply_aid_label_addr2": "Address Line 2",
      "apply_aid_hint_addr2": "e.g., Taman Bahagia",
      "apply_aid_label_postcode": "Postcode",
      "apply_aid_hint_postcode": "e.g., 50480",
      "apply_aid_label_city": "City",
      "apply_aid_hint_city": "Auto-populated from postcode",
      "apply_aid_label_state": "State",
      "apply_aid_hint_state": "Auto-populated from postcode",
      "apply_aid_label_residency": "Residency Status",
      "apply_aid_hint_residency": "Select your residency status",
      "apply_aid_residency_malaysian": "Malaysian",
      "apply_aid_residency_non_malaysian": "Non-Malaysian",
      "apply_aid_label_employment": "Employment Status",
      "apply_aid_hint_employment": "Select your employment status",
      "apply_aid_employment_employed": "Employed",
      "apply_aid_employment_unemployed": "Unemployed",
      "apply_aid_label_occupation": "Occupation",
      "apply_aid_hint_occupation": "e.g., Software Engineer",
      "apply_aid_label_income": "Monthly Income (RM)",
      "apply_aid_hint_income": "e.g., 3500",
      "apply_aid_label_is_asnaf": "Are you any of the asnaf?",
      "apply_aid_hint_is_asnaf": "Select an option",
      "apply_aid_label_asnaf_in": "Asnaf in",
      "apply_aid_hint_asnaf_in": "e.g., Lembaga Zakat Selangor",
      "apply_aid_label_justification": "Justification of Application",
      "apply_aid_hint_justification": "Explain why you need this financial aid...",
      "apply_aid_label_ekyc": "Verify Your Identity (eKYC)",
      "apply_aid_subtitle_ekyc": "Required for application",
      "apply_aid_ekyc_start": "Start eKYC Verification",
      "apply_aid_ekyc_complete": "Verification Complete",
      "apply_aid_label_proof_address": "Proof of Address (e.g. Utility Bill)",
      "apply_aid_upload_proof_address": "Upload Proof of Address",
      "apply_aid_label_proof_income": "Proof of Income",
      "apply_aid_upload_proof_income": "Upload Proof of Income",
      "apply_aid_upload_format": "Format: jpeg/jpg/pdf",
      "apply_aid_no_file_uploaded": "No file uploaded",
      "apply_aid_agreement1_title": "1. Eligibility and Accuracy of Information",
      "apply_aid_agreement1_content": "You confirm that all information provided in this application is true, complete, and accurate to the best of your knowledge. You understand that providing false or misleading information may result in the rejection of your application and may impact your eligibility for future assistance.",
      "apply_aid_agreement2_title": "2. Use of Financial Aid",
      "apply_aid_agreement2_content": "Financial aid provided through Kita Tongtong is intended solely for the purposes specified in the application, such as tuition fees, hostel fees, and other approved living expenses. You agree to use any funds or vouchers received only as directed and for approved expenses within the platform’s guidelines.",
      "apply_aid_agreement3_title": "3. Privacy and Data Usage",
      "apply_aid_agreement3_content": "By submitting this application, you consent to the collection, processing, and storage of your personal information as outlined in our Privacy Policy. Your information will be used only to assess your eligibility for aid, manage fund disbursement, and ensure compliance with platform policies.",
      "apply_aid_agreement4_title": "4. Review and Verification Process",
      "apply_aid_agreement4_content": "You acknowledge that Kita Tongtong may verify the information provided, which may include contacting relevant parties (such as universities, administrators) to validate your application. Failure to provide requested information within the specified timeline may result in application delays or denial.",

      "ok": "OK",
      "error": "Error",
      "applications_title": "Your Application Status",
      "track_applications_title": "Asnaf's Application Status",
      "applications_tab_all": "All",
      "applications_tab_submitted": "Submitted",
      "applications_tab_completed": "Completed",
      "applications_tab_rewards_issued": "Rewards Issued",
      "applications_search_hint": "Search by Application Code",
      "applications_sort_date": "Date",
      "applications_sort_name": "Name",
      "applications_sort_status": "Status",
      "applications_error_fetch": "Error: @error",
      "applications_no_apps_found": "No applications found.",
      "applications_no_apps_in_category": "No applications in this category",
      "applications_matching_search": " matching your search",
      "applications_no_date": "No date",
      "applications_no_code": "—",
      "applications_status_pending": "Pending",
      "applications_timeline_submitted": "Submitted",
      "applications_timeline_completed": "Completed",
      "applications_timeline_rewards": "Rewards",
      "status_unknown_date": "an unknown date",
      "status_no_app_found": "No application found.",
      "status_unknown_name": "Unknown",
      "status_unknown_code": "N/A",
      "status_no_reason": "No reason provided",
      "status_default_reward": "the specified aid",
      "status_accepted_subtitle": "Your application has been accepted. Reason: @reason",
      "status_rejected_subtitle": "Your application has been rejected. Reason: @reason",
      "status_reviewing_subtitle": "Your application is currently being reviewed.",
      "status_reward_issued_subtitle": "Your reward has been issued for @reward.",
      "status_reward_pending_subtitle": "Pending reward issuance.",
      "status_page_title": "Application Status",
      "status_label_app_code": "Application Code",
      "status_label_full_name": "Full Name",
      "status_title_submitted": "Application Submitted",
      "status_subtitle_submitted": "We received your application at @date.",
      "status_title_reviewed": "Application Reviewed",
      "status_title_rewards_issued": "Rewards Issued",

      "rewards_validity_month": "Valid for 1 month",
      "rewards_validity_days_single": "Valid for @count day",
      "rewards_validity_days_plural": "Valid for @count days",
      "rewards_expired": "Expired",
      "rewards_no_user_found": "No user found.",
      "rewards_no_user_data_found": "No user data found.",
      "rewards_section_title": "Voucher granted from application!",
      "rewards_no_admin_rewards": "No admin-issued rewards available.",
      "rewards_my_claimed_vouchers": "Claimed from points",
      "rewards_no_claimed_vouchers": "No claimed vouchers available.",
      "rewards_redeemed_on": "Redeemed on:\n@date",
      "rewards_invalid_voucher": "Invalid voucher value.",
      "rewards_image_error": "Image Error",
      "rewards_admin_issued": "Admin Issued Reward",
      "rewards_redeem_with": "Redeem with",
      "rewards_label": "Rewards",
      "rewards_recurring_subtitle": "Every: @period\nRedeemable from: @date",
      "rewards_redeemable_now": "Now",
      "rewards_tongtong_points": "Tongtong Points\n@points Pts",
      "rewards_points_to_redeem": "Points to Redeem",
      "rewards_details": "Details",
      "rewards_cash_voucher_details": "@value Cash Voucher\n@validity",
      "rewards_redeem_points_button": "Redeem Points",
      "rewards_redeem_your_points_title": "Redeem your Points!",
      "rewards_claim_button": "Claim",
      "rewards_join_activity_title": "Join Activity and Get Rewards!",
      "rewards_no_image": "No Image",
      "rewards_organised_by": "by @organiser",
      "rewards_join_button": "Join",
      "rewards_tab_redeem": "Redeem Rewards",

      "redeem_voucher_title": "Redeem Your Voucher",
      "redeem_items_loading_error": "Error loading items: @error",
      "redeem_no_items_available": "No items available at the moment.",
      "redeem_no_more_items_available": "No more items available based on current selections or voucher value.",
      "redeem_max_quantity_warning": "Maximum quantity for this item is 2.",
      "redeem_max_category_warning": "You can only add items from a maximum of 6 different categories for BARANGAN BERBUNGKUS.",
      "redeem_one_item_per_category_warning": "You can only add one item from the \"@category\" category.",
      "redeem_add_button": "Add",
      "redeem_checkout_button": "Checkout",
      "redeem_uncategorized": "Uncategorized",
      "redeem_unnamed_hamper": "Unnamed Hamper",
      "redeem_hamper_category": "Hamper",

      "order_summary_title": "Order Summary",
      "order_summary_exceed_voucher_error": "Cannot exceed voucher value.",
      "order_summary_not_logged_in_error": "User not logged in.",
      "order_summary_cart_empty_error": "Your cart is empty.",
      "order_summary_checkout_failed_error": "Checkout failed: @error",
      "order_summary_cart_is_empty": "Your cart is empty.",
      "order_summary_pickup_location_name": "Masjid MADAD (+60146019090)",
      "order_summary_pickup_location_address": "Masjid MADAD, Kampung Telok, 08000 Sungai Petani, Kedah",
      "order_summary_uncategorized": "Uncategorized",
      "order_summary_total_items": "Total (@count items)",
      "order_summary_place_order_button": "Place Order",

      "success_redeem_fetch_error": "Unable to fetch pickup code.",
      "success_redeem_title": "Your redemption is successful!",
      "success_redeem_congrats": "Congratulations! You have redeemed the item successfully. Your pickup code is",
      "success_redeem_pickup_details": "You can pick up your package at:\nMADAD Office\nOperating Hours: 9:00 AM - 5:00 PM\nPlease ensure you bring your redemption code and valid ID during pickup.",
      "success_redeem_track_order_button": "Track Order",

      "track_order_title": "Track Order",
      "track_order_tab_all": "All",
      "track_order_tab_to_process": "To Process",
      "track_order_tab_to_pickup": "To Pickup",
      "track_order_tab_completed": "Completed",
      "track_order_search_hint": "Search by Pickup Code",
      "track_order_sort_date": "Date",
      "track_order_sort_code": "Code",
      "track_order_fetch_error": "Error: @error",
      "track_order_no_orders_found": "No orders found.",
      "track_order_no_orders_in_category": "No orders in this category",
      "track_order_matching_search": " matching your search",
      "track_order_pickup_code_label": "Pickup Code: @code",
      "track_order_no_date": "No date",
      "track_order_not_applicable": "N/A",
      "track_order_status_completed": "Completed",
      "track_order_status_ready_for_pickup": "Ready for Pickup",
      "track_order_status_to_process": "To Process",
      "track_order_hamper_category": "Hamper",
      "track_order_unknown_item": "Unknown Item",

      "redemption_status_title": "Pickup Status",
      "redemption_status_order_not_found": "Order not found.",
      "redemption_status_pickup_code": "Pickup Code",
      "redemption_status_full_name": "Full Name",
      "redemption_status_user": "User",
      "redemption_status_qr_instruction": "Show this QR to the staff for pickup",
      "redemption_status_ok_button": "OK",
      "redemption_status_timeline_placed_title": "Order Placed",
      "redemption_status_timeline_placed_subtitle": "We have received your order.",
      "redemption_status_timeline_processed_title": "Order Processed",
      "redemption_status_timeline_processed_subtitle": "We are processing your order.",
      "redemption_status_timeline_pickup_title": "Ready to Pickup",
      "redemption_status_timeline_pickup_subtitle": "Your order is ready to pickup.",

      "track_rewards_title": "Track Rewards Status",
      "rewards_tab_all": "All",
      "rewards_tab_pending": "Pending",
      "rewards_tab_issued": "Issued",
      "rewards_tab_redeemed": "Redeemed",
      "rewards_search_hint": "Search by Name or Code",
      "rewards_error_fetch": "Error fetching rewards: @error",
      "rewards_no_items_found": "No rewards found.",
      "rewards_no_items_in_category": "No rewards in this category",
      "rewards_matching_search": " matching your search",

      "event_create_title": "Create Events",
      "event_list_title": "List of Events",
      "event_filter_upcoming": "Upcoming",
      "event_filter_ongoing": "Ongoing",
      "event_filter_past": "Past",
      "event_list_none_available": "No Events Available",
      "event_list_no_filtered_events": "No @filter Events",
      "event_deleted_snackbar": "@eventName deleted",
      "event_name_label": "Event Name",
      "event_points_label": "Points per attendance",
      "event_organiser_name_label": "Organiser's name",
      "event_organiser_number_label": "Organiser’s Number",
      "event_location_label": "Location",
      "event_map_error": "Could not open map.",
      "event_generate_qr_button": "Generate QR Code",
      "event_qr_dialog_title": "Event QR Code",
      "close": "Close",
      "event_form_title_create": "Create Event",
      "event_form_title_edit": "Edit Event",
      "event_form_subtitle": "Fill in the details below",
      "event_form_attendance_code_label": "Enter Attendance Code",
      "event_form_start_date_label": "Event’s start date & time",
      "event_form_end_date_label": "Event’s end date & time",
      "event_form_section_label": "Event Section",
      "event_form_custom_section_label": "Custom Section Name",
      "event_form_banner_label": "Event Banner",
      "event_form_validation_error": "Please fill in all required fields!",
      "event_map_picker_placeholder": "Pin location on map",
      "event_datetime_picker_placeholder": "Select Date & Time",
      "event_map_picker_title": "Pin Location",
      "event_map_search_hint": "Search for an address",
      "event_map_search_not_found": "Location not found.",
      "event_map_search_error": "Error finding location.",
      "event_map_confirm_validation": "Please select a location on the map.",
      "event_map_address_error": "Could not get address for the location.",
      "event_map_confirm_button": "Confirm Location",
      "event_section_upcoming": "Upcoming Activities",
      "event_section_others": "Others",
      "submit": "Submit",

      "eventDetail_title": "Event Details",
      "eventDetail_points_label": "Points to Earn",
      "eventDetail_starts_on_label": "Starts On",
      "eventDetail_ends_on_label": "Ends On",
      "eventDetail_location_label": "Location",
      "eventDetail_organiser_label": "Organiser",
      "eventDetail_contact_label": "Contact",
      "eventDetail_generate_qr_button": "Generate QR Code",
      "eventDetail_qr_dialog_title": "Event QR Code",
      "eventDetail_close_button": "Close",
      "eventDetail_code_not_available": "Attendance code is not available for this event.",
      "eventDetail_no_name": "No Name",
      "eventDetail_unknown": "Unknown",
      "eventDetail_not_applicable": "N/A",
      "eventDetail_no_location": "No location provided",

      "eventReview_success_title": "You have created an event!",
      "eventReview_success_subtitle": "It will be reflected at event page.",
      "eventReview_ok_button": "OK",

      "pickupItem_page_title": "Verify Pickup Code Here",
      "pickupItem_page_subtitle": "Scan QR or enter code to begin validation",
      "pickupItem_code_field_label": "Enter Pickup Code or Scan QR",
      "pickupItem_code_field_hint": "Enter code manually",
      "pickupItem_scan_qr_tooltip": "Scan QR Code",
      "pickupItem_verify_button": "Verify Asnaf Identity",
      "pickupItem_reward_redeemed_label": "Reward Redeemed",
      "pickupItem_asnaf_name_label": "Asnaf's Name",
      "pickupItem_asnaf_number_label": "Asnaf's Number",
      "pickupItem_submit_button": "Confirm & Submit Pickup",
      "pickupItem_error_scan": "Error opening QR scanner: ",
      "pickupItem_error_no_code": "Please enter or scan a pickup code.",
      "pickupItem_error_not_found": "Pickup code not found.",
      "pickupItem_error_already_picked_up": "This order has already been picked up.",
      "pickupItem_error_not_processed": "This order has not been processed by admin yet.",
      "pickupItem_error_no_ekyc": "Asnaf eKYC photo not found.",
      "pickupItem_error_validation_failed": "Face validation failed or was rejected by staff.",
      "pickupItem_error_generic": "An error occurred: ",
      "pickupItem_error_verify_first": "Please verify the Asnaf's identity first.",
      "pickupItem_error_submit_failed": "Failed to submit pickup: ",
      "pickupItem_success_validation": "Validation successful. Details loaded.",

      "orderProcessed_title": "Process Order",
      "orderProcessed_subtitle": "Process the order from Asnaf.",
      "orderProcessed_search_hint": "Search Asnaf",
      "orderProcessed_filter_all": "All",
      "orderProcessed_filter_pending": "Pending",
      "orderProcessed_filter_approved": "Approved",
      "orderProcessed_filter_rejected": "Rejected",
      "orderProcessed_sort_date": "Date",
      "orderProcessed_sort_name": "Name",
      "orderProcessed_sort_status": "Status",
      "orderProcessed_no_applications": "No applications found",
      "orderProcessed_status_approve": "Approve",
      "orderProcessed_status_pending": "Pending",
      "orderProcessed_unknown_user": "Unknown",
      "orderProcessed_no_code": "No Code",

      "stockItem_package_kasih": "Package Kasih",
      "stockItem_package_hamper": "Package Hamper",
      "stockItem_loading_dialog": "Submitting Package...",
      "stockItem_warning_title_validation": "Validation Error",
      "stockItem_warning_title_failed": "Validation Failed",
      "stockItem_warning_title_error": "An Error Occurred",
      "stockItem_warning_title_success": "Success",
      "stockItem_ok_button": "OK",
      "stockItem_edit_package_name_title": "Edit Package Name",
      "stockItem_edit_package_name_hint": "Enter new package name",
      "stockItem_cancel_button": "Cancel",
      "stockItem_update_button": "Update",
      "stockItem_add_kasih_title": "Add Package Kasih",
      "stockItem_item_name_label": "Item Name",
      "stockItem_search_hint": "Type to search item…",
      "stockItem_select_item_warning": "Please select an item before submitting.",
      "stockItem_create_package_error": "Error creating package: ",
      "stockItem_submit_package_button": "Submit Package",
      "stockItem_add_hamper_title": "Add Package Hamper",
      "stockItem_package_name_label": "Package Name",
      "stockItem_hamper_name_hint": "e.g., Hamper Raya Aidilfitri",
      "stockItem_voucher_value_label": "Voucher Value",
      "stockItem_items_label": "Items",
      "stockItem_hamper_name_warning": "Please enter a package name.",
      "stockItem_add_item_warning": "Please add at least one item to the hamper.",
      "stockItem_price_low_warning": "Price too low (RM @price). Need to add at least RM @diff more.",
      "stockItem_price_high_warning": "Item price too high (RM @price). Need to decrease item at least RM @diff.",
      "stockItem_submit_hamper_button": "Submit Hamper",
      "stockItem_kasih_list_title": "Available Packages Kasih",
      "stockItem_no_packages_available": "No packages available",
      "stockItem_unnamed_package": "Unnamed Package",
      "stockItem_no_category": "No Category",
      "stockItem_package_deleted": "\"@title\" has been deleted.",
      "stockItem_category_label": "Category: @category",
      "stockItem_price_label": "Price: RM @price",
      "stockItem_hamper_list_title": "Available Packages Hamper",
      "stockItem_no_hampers_available": "No hampers available",
      "stockItem_unnamed_hamper": "Unnamed Hamper",
      "stockItem_voucher_value_display": "Voucher Value: RM @value",

      "process_order_title": "Process Order",
      "update_order_no_data": "No data found for this order",
      "update_order_pickup_code_label": "Pickup Code",
      "update_order_application_code": "Application Code",
      "update_order_value_redeemed": "Value Redeemed",
      "update_order_items_redeemed": "Items Redeemed",
      "update_order_no_items": "No items to display",
      "update_order_prompt": "Have you done processing the order?",
      "update_order_dropdown_no": "No",
      "update_order_dropdown_yes": "Yes",
      "submit_button_text": "Submit",
      "update_order_select_yes_prompt": "Please select 'Yes' to proceed.",
      "update_order_success_message": "Order status updated successfully.",
      "update_order_failure_message": "Failed to update order status: @error",

      "verifyApp_title": "Verify Application",
      "verifyApp_tab_all": "All",
      "verifyApp_tab_pending": "Pending",
      "verifyApp_tab_verified": "Verified",
      "verifyApp_tab_rejected": "Rejected",
      "verifyApp_search_hint": "Search Asnaf...",
      "verifyApp_sort_date": "Date",
      "verifyApp_sort_name": "Name",
      "verifyApp_sort_status": "Status",
      "verifyApp_error_generic": "Error: @error",
      "verifyApp_no_apps_found": "No applications found",
      "verifyApp_no_apps_in_category": "No applications in this category",
      "verifyApp_search_no_match": " match your search.",
      "verifyApp_unknown_user": "Unknown",
      "verifyApp_no_date": "No date provided",
      "verifyApp_no_code": "No Code",
      "verifyApp_submitted_by": "Submitted by: @name",
      "verifyApp_status_approve": "Approve",
      "verifyApp_status_pending": "Pending",
      "verifyApp_status_reject": "Reject",

      "screening_title": "Screening Applicant",
      "screening_error_generic": "Error: @error",
      "screening_no_data": "No data found for this applicant.",
      "screening_update_success": "Application status updated successfully!",
      "screening_nric_label": "NRIC",
      "screening_mobile_label": "Mobile",
      "screening_email_label": "Email",
      "screening_address_label": "Address",
      "screening_residency_label": "Residency",
      "screening_employment_label": "Employment",
      "screening_occupation_label": "Occupation",
      "screening_income_label": "Income",
      "screening_asnaf_in_label": "Asnaf In",
      "screening_justification_label": "Justification",
      "screening_documents_title": "Uploaded Documents",
      "screening_doc_proof_address": "Proof of Address",
      "screening_doc_proof_income": "Proof of Income",
      "screening_doc_not_provided": "Not Provided",
      "screening_viewing_doc": "Viewing: @file",
      "screening_update_status_title": "Update Status",
      "screening_reason_title": "Reason / Remarks",
      "screening_reason_hint": "Enter reason for status update (optional)...",
      "screening_submit_button": "Submit Status",
      "screening_unknown_staff": "Unknown Staff",

      "issueReward_title": "Issue Reward",
      "issueReward_tab_all": "All",
      "issueReward_tab_pending": "Pending",
      "issueReward_tab_issued": "Issued",
      "issueReward_tab_redeemed": "Redeemed",
      "issueReward_search_hint": "Search by name or code...",
      "issueReward_sort_date": "Date",
      "issueReward_sort_name": "Name",
      "issueReward_sort_status": "Status",
      "issueReward_error_generic": "Error: @error",
      "issueReward_no_apps_found": "No applications found",
      "issueReward_no_rewards_in_category": "No rewards in this category",
      "issueReward_search_no_match": " match your search.",
      "issueReward_unknown_user": "Unknown",
      "issueReward_no_date": "No date",
      "issueReward_not_applicable": "N/A",

      "voucherIssuance_title": "Voucher Issuance",
      "voucherIssuance_app_not_found": "Application not found",
      "voucherIssuance_nric_label": "NRIC",
      "voucherIssuance_mobile_label": "Mobile",
      "voucherIssuance_employment_label": "Employment",
      "voucherIssuance_income_label": "Income",
      "voucherIssuance_address_label": "Address",
      "voucherIssuance_justification_label": "Justification",
      "voucherIssuance_submitted_by_staff": "Submitted by Staff: @name",
      "voucherIssuance_submitted_by_user": "Submitted by: @name",
      "voucherIssuance_reward_amount_label": "Reward Amount",
      "voucherIssuance_aid_recurrence_label": "Aid Recurrence",
      "voucherIssuance_recurring_switch_label": "Issue Recurring Aid",
      "voucherIssuance_recurrence_period_label": "Recurrence Period",
      "voucherIssuance_period_2_weeks": "2 Weeks",
      "voucherIssuance_period_1_month": "1 Month",
      "voucherIssuance_period_3_months": "3 Months",
      "voucherIssuance_period_6_months": "6 Months",
      "voucherIssuance_period_9_months": "9 Months",
      "voucherIssuance_period_1_year": "1 Year",
      "voucherIssuance_submit_button": "Issue Reward",
      "voucherIssuance_update_success": "Reward details updated successfully!",
      "voucherIssuance_update_fail": "Failed to update reward details: @error",
      "voucherIssuance_data_load_error": "Error loading initial data: @error",

      "manageStaffs_title": "Manage Staffs",
      "manageStaffs_subtitle": "Track users you’ve registered or managed.",
      "manageStaffs_search_hint": "Search User",
      "manageStaffs_filter_button": "Filter",
      "manageStaffs_role_admin": "Admin",
      "manageStaffs_role_staff": "Staff",
      "manageStaffs_role_asnaf": "Asnaf",
      "manageStaffs_sort_date": "Date",
      "manageStaffs_sort_name": "Name",
      "manageStaffs_error_generic": "Error: @error",
      "manageStaffs_no_users_found": "No users found.",
      "manageStaffs_unknown_user": "Unknown",
      "manageStaffs_no_email": "No Email",

      "staffDetails_title": "Manage Users",
      "staffDetails_no_data": "No data found for this user.",
      "staffDetails_update_success": "User role updated successfully!",
      "staffDetails_update_error": "Error updating role: @error",
      "staffDetails_label_fullName": "Full Name",
      "staffDetails_label_nric": "NRIC",
      "staffDetails_label_email": "Email",
      "staffDetails_label_phone": "Phone",
      "staffDetails_label_address": "Address",
      "staffDetails_label_role": "Role",
      "staffDetails_label_account_created": "Account Created",
      "staffDetails_label_last_login": "Last Login",
      "staffDetails_label_ekyc_verified": "eKYC Verified",
      "staffDetails_role_admin": "Admin",
      "staffDetails_role_staff": "Staff",
      "staffDetails_role_asnaf": "Asnaf",
      "staffDetails_submit_button": "Submit",
      "staffDetails_not_applicable": "No",

      "viewReports_title": "Dashboard Reports",
      "viewReports_subtitle": "Actionable insights for strategic decisions.",
      "viewReports_chart_no_data": "No data available to display.",
      "viewReports_funnel_title": "Application Funnel Analysis",
      "viewReports_funnel_total": "Total",
      "viewReports_funnel_pending": "Pending",
      "viewReports_funnel_approved": "Approved",
      "viewReports_funnel_rejected": "Rejected",
      "viewReports_region_title": "Applicants by Region",
      "viewReports_region_other": "Other",
      "viewReports_donations_title": "Monthly Donation Analysis",
      "viewReports_redemption_title": "Redemption Popularity",
      "viewReports_redemption_summary": "Summary",
      "viewReports_redemption_kasih": "Kasih",
      "viewReports_redemption_hamper": "Hamper",
      "viewReports_kasih_detail_title": "Top 10 Redeemed Kasih Items",
      "viewReports_hamper_detail_title": "Redeemed Hampers",
      "viewReports_chatbot_title": "BI Assistant",
      "viewReports_chatbot_hint": "Ask about the data...",
      "viewReports_chatbot_error": "Sorry, I couldn't get a response.",
      "viewReports_chatbot_generic_error": "Error: @error"
    },
    'ms': {
      // General
      'ok': 'OK',
      'yes': 'Ya',
      'no': 'Tidak',
      'submit': 'Hantar',
      'next': 'Seterusnya',
      'cancel': 'Batal',
      'error': 'Ralat',
      'success': 'Berjaya',
      'pending': 'Menunggu',
      'approve': 'Lulus',
      'reject': 'Tolak',
      'approved': 'Diluluskan',
      'disapprove': 'Tidak Lulus',
      'issued': 'Diberi',
      'all': 'Semua',
      'date': 'Tarikh',
      'name': 'Nama',
      'status': 'Status',
      'search': 'Cari',
      'filter': 'Tapis',
      'sort': 'Susun',

      // HomePage
      'search_hint_admin': 'Admin di sini...',
      'search_hint_staff': 'Staf di sini...',
      'search_hint_asnaf': 'Asnaf di sini...',
      'upcoming_activities': 'Aktiviti Akan Datang',
      'get_points': 'Dapat @points mata',
      'no_location': 'Tiada lokasi',
      'search_page': 'Halaman Carian',
      'shopping_page': 'Halaman Membeli-belah',
      'inbox_page': 'Halaman Peti Masuk',
      'profile_page': 'Halaman Profil',

      // LoginPage
      'login_title': 'Daftar atau log masuk',
      'login_subtitle': 'Pilih kaedah pilihan anda untuk meneruskan',
      'login_google': 'Teruskan dengan Google',
      'login_email': 'Teruskan dengan E-mel',
      'login_not_implemented': 'Log masuk e-mel belum dilaksanakan.',
      'login_failed': 'Log masuk Google dibatalkan atau gagal.',
      'login_error': 'Ralat log masuk Google: @error',

      // AmountPage
      'help_asnaf_by_amount': 'Bantu Asnaf melalui Jumlah',
      'other': 'Lain-lain',
      'donor_info': 'Maklumat Penderma',
      'tax_exemption_q': 'Adakah anda mahu surat pengecualian cukai dihantar kepada anda?',
      'designation': 'Jawatan',
      'select': 'Pilih',
      'full_name': 'Nama Penuh',
      'enter_full_name': 'Masukkan nama penuh',
      'email': 'E-mel',
      'enter_email': 'Masukkan e-mel',
      'contact_number': 'Nombor Hubungan',
      'enter_mobile_number': 'Masukkan nombor telefon bimbit',
      'payment_method': 'Kaedah Pembayaran',
      'card': 'Kad',
      'fpx': 'FPX',
      'donate_now': 'Derma Sekarang',
      'fix_errors_prompt': 'Sila betulkan ralat sebelum menghantar.',
      'select_amount_prompt': 'Sila pilih atau masukkan jumlah.',
      'valid_amount_prompt': 'Sila masukkan jumlah yang sah.',
      'donation_processing': 'Memproses derma... Sila ikut arahan pembayaran.',
      'full_name_required': 'Nama penuh diperlukan',
      'email_required': 'E-mel diperlukan',
      'valid_email_prompt': 'Masukkan alamat e-mel yang sah',
      'contact_required': 'Nombor hubungan diperlukan',
      'contact_must_be_digits': 'Mestilah 9-10 digit',
      'amount_must_be_number': 'Sila masukkan nombor',
      'amount_gt_one': 'Jumlah mesti lebih besar daripada RM1',

      // ApplicationReviewScreen
      'app_under_review': 'Permohonan anda sedang disemak!',
      'app_review_notify': 'Kami sedang menyemak permohonan anda.\nKami akan memaklumkan keputusan dalam 6-7 hari bekerja.',

      // ApplicationsScreen
      'your_app_status': 'Status Permohonan Anda',
      'track_app_submitted': 'Jejaki permohonan yang telah anda hantar.',
      'search_code': 'Cari Kod',
      'no_applications_found': 'Tiada permohonan ditemui',
      'submitted': 'Dihantar',
      'completed': 'Selesai',
      'rewards': 'Ganjaran',

      "dashboard_verify_applications": "Sahkan Permohonan",
      "dashboard_issue_reward": "Berikan Ganjaran",
      "dashboard_view_reports": "Lihat Laporan",
      "dashboard_manage_user": "Urus Pengguna",
      "dashboard_help_asnaf": "Bantu Asnaf",
      "dashboard_apply_aid": "Mohon Bantuan",
      "dashboard_application_status": "Status Permohonan",
      "dashboard_redeem_rewards": "Tebus Ganjaran",
      "dashboard_submit_application": "Hantar Permohonan",
      "dashboard_asnaf_vouchers": "Baucar Asnaf",
      "dashboard_monitor_applications": "Pantau Permohonan",
      "dashboard_manage_events": "Urus Acara",
      "userpoints_points": "Mata",
      "userpoints_pickup_item": "Ambil Barangan",
      "userpoints_checkin_event": "Daftar Masuk Acara",
      "userpoints_help_attendance": "Bantu Kehadiran",
      "userpoints_checkin_description": "Dapatkan mata dengan mengesahkan\nkehadiran anda",

      "login_title": "Daftar atau log masuk",
      "login_subtitle": "Pilih kaedah pilihan anda untuk meneruskan",
      "login_google": "Teruskan dengan Google",
      "login_email": "Teruskan dengan E-mel",
      "login_failed": "Log masuk Google dibatalkan atau gagal.",
      "login_error": "Ralat log masuk Google: @error",
      "login_not_implemented": "Log masuk e-mel belum dilaksanakan.",
      "profile_set_name_hint": "Tetapkan nama anda",
      "profile_change_photo": "Tukar gambar profil",
      "profile_no_email": "Tiada E-mel Tersedia",
      "profile_set_username": "Tetapkan nama pengguna",
      "profile_mobile_number": "Nombor Telefon Bimbit",
      "profile_nric": "NRIC",
      "profile_home_address": "Alamat Rumah",
      "profile_city": "Bandar",
      "profile_postcode": "Poskod",
      "profile_logout": "Log keluar",
      "profile_login": "Log masuk",

      "help_asnaf_by": "Bantu Asnaf Melalui...",
      "help_asnaf_amount": "Jumlah",
      "help_asnaf_amount_desc": "Anda boleh menyumbang sebarang jumlah yang anda inginkan. Setiap sumbangan, tidak kira sekecil mana, akan membawa perubahan.",
      "help_asnaf_package": "Pakej",
      "help_asnaf_package_desc": "Pilih daripada senarai baucar pakej pra-tetap yang anda sanggup taja. Pakej-pakej ini menyediakan barangan keperluan kepada Asnaf.",
      "help_asnaf_item_bank": "Bank Makanan/Barangan",
      "help_asnaf_item_bank_desc": "Sumbangkan sebarang makanan atau barangan yang anda ada ke pusat MADAD. Ia akan diagihkan kepada Asnaf.",
      "package_page_title": "Bantu Asnaf melalui Pakej",
      "package_no_packages": "Tiada pakej tersedia",
      "package_choice": "Pilihan",
      "package_quantity": "Kuantiti",
      "package_value": "Nilai (RM)",
      "package_total": "Jumlah:",
      "package_overall_amount": "Jumlah Keseluruhan (RM):",
      "pay_package_title": "Bantu Asnaf melalui Pakej (@count dipilih)",
      "pay_package_unnamed_hamper": "Hamper Tanpa Nama",
      "pay_package_config_error": "Ralat konfigurasi pembayaran. Sila hubungi sokongan.",
      "pay_package_initiation_error": "Ralat permulaan pembayaran. Sila cuba lagi.",
      "pay_package_failed_initiation": "Gagal untuk memulakan pembayaran.",
      "pay_package_could_not_open": "Tidak dapat membuka halaman pembayaran.",
      "pay_package_processing": "Memproses derma... Sila ikut arahan pembayaran.",

      "food_item_bank_title": "Bank Makanan / Barangan",
      "food_item_bank_submit_success": "Berjaya dihantar!",
      "food_item_bank_submit_error": "Ralat: @error",
      "food_item_bank_required_field": "Diperlukan",
      "food_item_bank_type": "Jenis",
      "food_item_bank_type_food": "Makanan",
      "food_item_bank_type_item": "Barangan",
      "food_item_bank_item_name_label": "Nama Barangan",
      "food_item_bank_item_name_hint": "Masukkan nama barangan",
      "food_item_bank_item_type_label": "Jenis Barangan",
      "food_item_bank_item_type_clothes": "Pakaian",
      "food_item_bank_item_type_accessory": "Aksesori",
      "food_item_bank_item_type_baby": "Barangan Bayi",
      "food_item_bank_item_type_school": "Barangan Sekolah",
      "food_item_bank_item_type_other": "Lain-lain",
      "food_item_bank_number_of_items": "Bilangan Barangan",
      "food_item_bank_condition_new": "Baru",
      "food_item_bank_condition_used": "Terpakai",
      "food_item_bank_estimated_value": "Anggaran Nilai (RM)",
      "food_item_bank_giver_name_label": "Nama Pemberi",
      "food_item_bank_giver_name_hint": "Masukkan nama anda",
      "food_item_bank_phone_label": "Nombor Telefon",
      "food_item_bank_phone_hint": "Masukkan nombor telefon anda",
      "food_item_bank_email_label": "E-mel",
      "food_item_bank_email_hint": "Masukkan e-mel anda",
      "food_item_bank_tax_question": "Adakah anda mahukan surat pengecualian cukai?",
      "food_item_bank_picture_label": "Gambar Makanan/Barangan",
      "food_item_bank_upload_tap": "Ketik untuk muat naik imej",
      "food_item_bank_upload_format": "Format: jpeg/jpg/png",

      "bottom_nav_login_prompt": "Sila log masuk untuk melihat profil anda.",
      "bottom_nav_home": "Utama",
      "bottom_nav_track_order": "Jejak Pesanan",
      "bottom_nav_order": "Pesanan",
      "bottom_nav_stock": "Stok",
      "bottom_nav_shopping": "Membeli-belah",
      "bottom_nav_inbox": "Peti Masuk",
      "bottom_nav_profile": "Profil",

      "ok": "OK",
      "next": "Seterusnya",
      "submit": "Hantar",
      "yes": "Ya",
      "no": "Tidak",

      "app_review_title": "Permohonan anda sedang disemak!",
      "app_review_subtitle": "Kami sedang menyemak permohonan anda.\nKami akan memaklumkan keputusan anda dalam tempoh 6-7 hari perniagaan.",

      "ekyc_title": "Pengesahan eKYC",
      "ekyc_error_missing_images": "Sila ambil gambar NRIC dan Swafoto.",
      "ekyc_error_nric_validation_failed": "Pengesahan NRIC gagal. Sila pastikan gambar jelas, merangkumi wajah, dan mempunyai teks yang boleh dibaca dengan nombor NRIC dan nama yang sah.",
      "ekyc_error_selfie_validation_failed": "Pengesahan swafoto gagal. Sila pastikan wajah anda kelihatan jelas dalam swafoto.",
      "ekyc_error_generic": "Ralat berlaku semasa proses eKYC: @error",
      "ekyc_validation_error_title": "Ralat Pengesahan",
      "ekyc_capture_nric_title": "1. Ambil Gambar NRIC",
      "ekyc_capture_selfie_title": "2. Ambil Swafoto",
      "ekyc_verify_submit_button": "Sahkan & Hantar",
      "ekyc_tap_to_open_camera": "Ketik untuk membuka kamera",

      "apply_aid_submit_success": "Permohonan berjaya dihantar!",
      "apply_aid_submit_fail": "Gagal menghantar permohonan. Sila cuba lagi.",
      "apply_aid_ekyc_success": "Pengesahan eKYC Berjaya!",
      "apply_aid_validation_mobile": "Sila masukkan nombor telefon bimbit Malaysia yang sah.",
      "apply_aid_validation_addr1": "Sila masukkan Baris Alamat 1.",
      "apply_aid_validation_postcode": "Sila masukkan poskod 5 digit yang sah.",
      "apply_aid_validation_city_state": "Bandar dan Negeri akan diisi secara automatik daripada poskod yang sah.",
      "apply_aid_validation_residency": "Sila pilih status pemastautin anda.",
      "apply_aid_validation_employment": "Sila pilih status pekerjaan anda.",
      "apply_aid_validation_occupation": "Sila masukkan pekerjaan anda.",
      "apply_aid_validation_income": "Sila masukkan pendapatan bulanan anda.",
      "apply_aid_validation_income_numeric": "Sila masukkan nombor yang sah untuk pendapatan bulanan.",
      "apply_aid_validation_income_limit": "Pendapatan bulanan tidak boleh melebihi RM 8,000 untuk layak menerima bantuan.",
      "apply_aid_validation_is_asnaf": "Sila nyatakan jika anda seorang Asnaf.",
      "apply_aid_validation_asnaf_in": "Sila nyatakan di mana anda berdaftar sebagai Asnaf.",
      "apply_aid_validation_justification": "Sila berikan justifikasi untuk permohonan anda.",
      "apply_aid_validation_ekyc_incomplete": "Sila lengkapkan pengesahan eKYC terlebih dahulu.",
      "apply_aid_validation_proof_address": "Sila muat naik Bukti Alamat anda.",
      "apply_aid_validation_proof_income": "Sila muat naik Bukti Pendapatan anda.",
      "apply_aid_validation_all_fields": "Sila pastikan semua medan diisi dengan betul sebelum menghantar.",
      "apply_aid_step1_title": "Kongsi butiran peribadi anda",
      "apply_aid_step1_subtitle": "Isi butiran peribadi anda untuk memulakan permohonan",
      "apply_aid_step2_title": "Semak kelayakan anda",
      "apply_aid_step2_subtitle": "Jawab beberapa soalan mudah untuk melihat sama ada anda memenuhi kriteria kelayakan kami",
      "apply_aid_step3_title": "Muat naik dokumen yang diperlukan",
      "apply_aid_step3_subtitle": "Kami perlu mengesahkan identiti dan status kewangan anda. Sila muat naik dokumen yang diperlukan",
      "apply_aid_step4_title": "Semak semula dokumen anda",
      "apply_aid_step4_subtitle": "Sila semak dokumen yang dimuat naik sebelum menghantar.",
      "apply_aid_step5_title": "Perjanjian Kita Tongtong",
      "apply_aid_step5_subtitle": "Sila baca dan bersetuju dengan terma dan syarat sebelum menghantar permohonan anda.",
      "apply_aid_label_email": "E-mel",
      "apply_aid_hint_email": "Alamat e-mel anda",
      "apply_aid_label_mobile": "Nombor Telefon Bimbit",
      "apply_aid_hint_mobile": "123456789",
      "apply_aid_label_addr1": "Baris Alamat 1",
      "apply_aid_hint_addr1": "cth., Lot 123, Jalan Merdeka",
      "apply_aid_label_addr2": "Baris Alamat 2",
      "apply_aid_hint_addr2": "cth., Taman Bahagia",
      "apply_aid_label_postcode": "Poskod",
      "apply_aid_hint_postcode": "cth., 50480",
      "apply_aid_label_city": "Bandar",
      "apply_aid_hint_city": "Diisi automatik dari poskod",
      "apply_aid_label_state": "Negeri",
      "apply_aid_hint_state": "Diisi automatik dari poskod",
      "apply_aid_label_residency": "Status Pemastautin",
      "apply_aid_hint_residency": "Pilih status pemastautin anda",
      "apply_aid_residency_malaysian": "Warganegara Malaysia",
      "apply_aid_residency_non_malaysian": "Bukan Warganegara Malaysia",
      "apply_aid_label_employment": "Status Pekerjaan",
      "apply_aid_hint_employment": "Pilih status pekerjaan anda",
      "apply_aid_employment_employed": "Bekerja",
      "apply_aid_employment_unemployed": "Tidak Bekerja",
      "apply_aid_label_occupation": "Pekerjaan",
      "apply_aid_hint_occupation": "cth., Jurutera Perisian",
      "apply_aid_label_income": "Pendapatan Bulanan (RM)",
      "apply_aid_hint_income": "cth., 3500",
      "apply_aid_label_is_asnaf": "Adakah anda tergolong dalam mana-mana asnaf?",
      "apply_aid_hint_is_asnaf": "Pilih satu pilihan",
      "apply_aid_label_asnaf_in": "Asnaf di",
      "apply_aid_hint_asnaf_in": "cth., Lembaga Zakat Selangor",
      "apply_aid_label_justification": "Justifikasi Permohonan",
      "apply_aid_hint_justification": "Terangkan mengapa anda memerlukan bantuan kewangan ini...",
      "apply_aid_label_ekyc": "Sahkan Identiti Anda (eKYC)",
      "apply_aid_subtitle_ekyc": "Diperlukan untuk permohonan",
      "apply_aid_ekyc_start": "Mula Pengesahan eKYC",
      "apply_aid_ekyc_complete": "Pengesahan Selesai",
      "apply_aid_label_proof_address": "Bukti Alamat (cth. Bil Utiliti)",
      "apply_aid_upload_proof_address": "Muat Naik Bukti Alamat",
      "apply_aid_label_proof_income": "Bukti Pendapatan",
      "apply_aid_upload_proof_income": "Muat Naik Bukti Pendapatan",
      "apply_aid_upload_format": "Format: jpeg/jpg/pdf",
      "apply_aid_no_file_uploaded": "Tiada fail dimuat naik",
      "apply_aid_agreement1_title": "1. Kelayakan dan Ketepatan Maklumat",
      "apply_aid_agreement1_content": "Anda mengesahkan bahawa semua maklumat yang diberikan dalam permohonan ini adalah benar, lengkap, dan tepat sepanjang pengetahuan anda. Anda faham bahawa memberikan maklumat palsu atau mengelirukan boleh mengakibatkan penolakan permohonan anda dan boleh menjejaskan kelayakan anda untuk bantuan pada masa hadapan.",
      "apply_aid_agreement2_title": "2. Penggunaan Bantuan Kewangan",
      "apply_aid_agreement2_content": "Bantuan kewangan yang diberikan melalui Kita Tongtong adalah bertujuan semata-mata untuk tujuan yang dinyatakan dalam permohonan, seperti yuran pengajian, yuran asrama, dan perbelanjaan sara hidup lain yang diluluskan. Anda bersetuju untuk menggunakan sebarang dana atau baucar yang diterima hanya seperti yang diarahkan dan untuk perbelanjaan yang diluluskan mengikut garis panduan platform.",
      "apply_aid_agreement3_title": "3. Privasi dan Penggunaan Data",
      "apply_aid_agreement3_content": "Dengan menghantar permohonan ini, anda bersetuju dengan pengumpulan, pemprosesan, dan penyimpanan maklumat peribadi anda seperti yang digariskan dalam Dasar Privasi kami. Maklumat anda akan digunakan hanya untuk menilai kelayakan anda untuk bantuan, menguruskan pengagihan dana, dan memastikan pematuhan terhadap dasar platform.",
      "apply_aid_agreement4_title": "4. Proses Semakan dan Pengesahan",
      "apply_aid_agreement4_content": "Anda mengakui bahawa Kita Tongtong boleh mengesahkan maklumat yang diberikan, yang mungkin termasuk menghubungi pihak berkaitan (seperti universiti, pentadbir) untuk mengesahkan permohonan anda. Kegagalan untuk memberikan maklumat yang diminta dalam tempoh masa yang ditetapkan boleh mengakibatkan kelewatan atau penafian permohonan.",

      "ok": "OK",
      "error": "Ralat",
      "applications_title": "Status Permohonan Anda",
      "track_applications_title": "Status Permohonan Asnaf",
      "applications_tab_all": "Semua",
      "applications_tab_submitted": "Dihantar",
      "applications_tab_completed": "Selesai",
      "applications_tab_rewards_issued": "Ganjaran Diberi",
      "applications_search_hint": "Cari mengikut Kod Permohonan",
      "applications_sort_date": "Tarikh",
      "applications_sort_name": "Nama",
      "applications_sort_status": "Status",
      "applications_error_fetch": "Ralat: @error",
      "applications_no_apps_found": "Tiada permohonan ditemui.",
      "applications_no_apps_in_category": "Tiada permohonan dalam kategori ini",
      "applications_matching_search": " yang sepadan dengan carian anda",
      "applications_no_date": "Tiada tarikh",
      "applications_no_code": "—",
      "applications_status_pending": "Menunggu",
      "applications_timeline_submitted": "Dihantar",
      "applications_timeline_completed": "Selesai",
      "applications_timeline_rewards": "Ganjaran",
      "status_unknown_date": "tarikh tidak diketahui",
      "status_no_app_found": "Tiada permohonan ditemui.",
      "status_unknown_name": "Tidak diketahui",
      "status_unknown_code": "T/B",
      "status_no_reason": "Tiada sebab diberikan",
      "status_default_reward": "bantuan yang dinyatakan",
      "status_accepted_subtitle": "Permohonan anda telah diterima. Sebab: @reason",
      "status_rejected_subtitle": "Permohonan anda telah ditolak. Sebab: @reason",
      "status_reviewing_subtitle": "Permohonan anda sedang disemak.",
      "status_reward_issued_subtitle": "Ganjaran anda telah diberi untuk @reward.",
      "status_reward_pending_subtitle": "Menunggu pengeluaran ganjaran.",
      "status_page_title": "Status Permohonan",
      "status_label_app_code": "Kod Permohonan",
      "status_label_full_name": "Nama Penuh",
      "status_title_submitted": "Permohonan Dihantar",
      "status_subtitle_submitted": "Kami menerima permohonan anda pada @date.",
      "status_title_reviewed": "Permohonan Disemak",
      "status_title_rewards_issued": "Ganjaran Diberi",

      "rewards_validity_month": "Sah untuk 1 bulan",
      "rewards_validity_days_single": "Sah untuk @count hari",
      "rewards_validity_days_plural": "Sah untuk @count hari",
      "rewards_expired": "Tamat Tempoh",
      "rewards_no_user_found": "Pengguna tidak ditemui.",
      "rewards_no_user_data_found": "Data pengguna tidak ditemui.",
      "rewards_section_title": "Baucer dari permohonan anda!",
      "rewards_no_admin_rewards": "Tiada ganjaran diberi tersedia.",
      "rewards_my_claimed_vouchers": "Ditebus dari pmata",
      "rewards_no_claimed_vouchers": "Tiada baucar yang ditebus tersedia.",
      "rewards_redeemed_on": "Ditebus pada:\n@date",
      "rewards_invalid_voucher": "Nilai baucar tidak sah.",
      "rewards_image_error": "Ralat Imej",
      "rewards_admin_issued": "Ganjaran Diberi Admin",
      "rewards_redeem_with": "Tebus dengan",
      "rewards_label": "Ganjaran",
      "rewards_recurring_subtitle": "Setiap: @period\nBoleh ditebus dari: @date",
      "rewards_redeemable_now": "Sekarang",
      "rewards_tongtong_points": "Mata Tongtong\n@points Mata",
      "rewards_points_to_redeem": "Mata untuk Ditebus",
      "rewards_details": "Butiran",
      "rewards_cash_voucher_details": "Baucar Tunai @value\n@validity",
      "rewards_redeem_points_button": "Tebus Mata",
      "rewards_redeem_your_points_title": "Tebus Mata Anda!",
      "rewards_claim_button": "Tuntut",
      "rewards_join_activity_title": "Sertai Aktiviti dan Dapatkan Ganjaran!",
      "rewards_no_image": "Tiada Imej",
      "rewards_organised_by": "oleh @organiser",
      "rewards_join_button": "Sertai",
      "rewards_tab_redeem": "Tebus Ganjaran",

      "redeem_voucher_title": "Tebus Baucar Anda",
      "redeem_items_loading_error": "Ralat memuatkan barangan: @error",
      "redeem_no_items_available": "Tiada barangan tersedia pada masa ini.",
      "redeem_no_more_items_available": "Tiada lagi barangan tersedia berdasarkan pilihan semasa atau nilai baucar.",
      "redeem_max_quantity_warning": "Kuantiti maksimum untuk barangan ini ialah 2.",
      "redeem_max_category_warning": "Anda hanya boleh menambah barangan daripada maksimum 6 kategori berbeza untuk BARANGAN BERBUNGKUS.",
      "redeem_one_item_per_category_warning": "Anda hanya boleh menambah satu barangan dari kategori \"@category\".",
      "redeem_add_button": "Tambah",
      "redeem_checkout_button": "Tebus",
      "redeem_uncategorized": "Tidak Berkategori",
      "redeem_unnamed_hamper": "Hamper Tanpa Nama",
      "redeem_hamper_category": "Hamper",

      "order_summary_title": "Ringkasan Pesanan",
      "order_summary_exceed_voucher_error": "Tidak boleh melebihi nilai baucar.",
      "order_summary_not_logged_in_error": "Pengguna belum log masuk.",
      "order_summary_cart_empty_error": "Troli anda kosong.",
      "order_summary_checkout_failed_error": "Daftar keluar gagal: @error",
      "order_summary_cart_is_empty": "Troli anda kosong.",
      "order_summary_pickup_location_name": "Masjid MADAD (+60146019090)",
      "order_summary_pickup_location_address": "Masjid MADAD, Kampung Telok, 08000 Sungai Petani, Kedah",
      "order_summary_uncategorized": "Tidak Berkategori",
      "order_summary_total_items": "Jumlah (@count barang)",
      "order_summary_place_order_button": "Buat Pesanan",

      "success_redeem_fetch_error": "Tidak dapat mengambil kod pengambilan.",
      "success_redeem_title": "Penebusan anda berjaya!",
      "success_redeem_congrats": "Tahniah! Anda telah berjaya menebus item tersebut. Kod pengambilan anda ialah",
      "success_redeem_pickup_details": "Anda boleh mengambil pakej anda di:\nPejabat MADAD\nWaktu Operasi: 9:00 PG - 5:00 PTG\nSila pastikan anda membawa kod penebusan dan ID yang sah semasa pengambilan.",
      "success_redeem_track_order_button": "Jejak Pesanan",

      "track_order_title": "Jejak Pesanan",
      "track_order_tab_all": "Semua",
      "track_order_tab_to_process": "Proses",
      "track_order_tab_to_pickup": "Siap",
      "track_order_tab_completed": "Selesai",
      "track_order_search_hint": "Cari mengikut Kod Pengambilan",
      "track_order_sort_date": "Tarikh",
      "track_order_sort_code": "Kod",
      "track_order_fetch_error": "Ralat: @error",
      "track_order_no_orders_found": "Tiada pesanan ditemui.",
      "track_order_no_orders_in_category": "Tiada pesanan dalam kategori ini",
      "track_order_matching_search": " sepadan dengan carian anda",
      "track_order_pickup_code_label": "Kod Pengambilan: @code",
      "track_order_no_date": "Tiada tarikh",
      "track_order_not_applicable": "T/B",
      "track_order_status_completed": "Selesai",
      "track_order_status_ready_for_pickup": "Sedia untuk Diambil",
      "track_order_status_to_process": "Untuk Diproses",
      "track_order_hamper_category": "Hamper",
      "track_order_unknown_item": "Item Tidak Diketahui",

      "redemption_status_title": "Status Pengambilan",
      "redemption_status_order_not_found": "Pesanan tidak ditemui.",
      "redemption_status_pickup_code": "Kod Pengambilan",
      "redemption_status_full_name": "Nama Penuh",
      "redemption_status_user": "Pengguna",
      "redemption_status_qr_instruction": "Tunjukkan QR ini kepada staf untuk pengambilan",
      "redemption_status_ok_button": "OK",
      "redemption_status_timeline_placed_title": "Pesanan Dibuat",
      "redemption_status_timeline_placed_subtitle": "Kami telah menerima pesanan anda.",
      "redemption_status_timeline_processed_title": "Pesanan Diproses",
      "redemption_status_timeline_processed_subtitle": "Kami sedang memproses pesanan anda.",
      "redemption_status_timeline_pickup_title": "Sedia untuk Diambil",
      "redemption_status_timeline_pickup_subtitle": "Pesanan anda sedia untuk diambil.",

      "track_rewards_title": "Jejak Status Ganjaran",
      "rewards_tab_all": "Semua",
      "rewards_tab_pending": "Menunggu",
      "rewards_tab_issued": "Diberi",
      "rewards_tab_redeemed": "Ditebus",
      "rewards_search_hint": "Cari ikut Nama atau Kod",
      "rewards_error_fetch": "Ralat memuatkan ganjaran: @error",
      "rewards_no_items_found": "Tiada ganjaran ditemui.",
      "rewards_no_items_in_category": "Tiada ganjaran dalam kategori ini",
      "rewards_matching_search": " sepadan dengan carian anda",

      "event_create_title": "Cipta Acara",
      "event_list_title": "Senarai Acara",
      "event_filter_upcoming": "Akan Datang",
      "event_filter_ongoing": "Berlangsung",
      "event_filter_past": "Lepas",
      "event_list_none_available": "Tiada Acara Tersedia",
      "event_list_no_filtered_events": "Tiada Acara @filter",
      "event_deleted_snackbar": "@eventName dipadam",
      "event_name_label": "Nama Acara",
      "event_points_label": "Mata setiap kehadiran",
      "event_organiser_name_label": "Nama Penganjur",
      "event_organiser_number_label": "Nombor Penganjur",
      "event_location_label": "Lokasi",
      "event_map_error": "Tidak dapat membuka peta.",
      "event_generate_qr_button": "Jana Kod QR",
      "event_qr_dialog_title": "Kod QR Acara",
      "close": "Tutup",
      "event_form_title_create": "Cipta Acara",
      "event_form_title_edit": "Sunting Acara",
      "event_form_subtitle": "Isi butiran di bawah",
      "event_form_attendance_code_label": "Masukkan Kod Kehadiran",
      "event_form_start_date_label": "Tarikh & masa mula Acara",
      "event_form_end_date_label": "Tarikh & masa tamat Acara",
      "event_form_section_label": "Seksyen Acara",
      "event_form_custom_section_label": "Nama Seksyen Tersuai",
      "event_form_banner_label": "Sepanduk Acara",
      "event_form_validation_error": "Sila isi semua medan yang diperlukan!",
      "event_map_picker_placeholder": "Pin lokasi pada peta",
      "event_datetime_picker_placeholder": "Pilih Tarikh & Masa",
      "event_map_picker_title": "Pin Lokasi",
      "event_map_search_hint": "Cari alamat",
      "event_map_search_not_found": "Lokasi tidak dijumpai.",
      "event_map_search_error": "Ralat mencari lokasi.",
      "event_map_confirm_validation": "Sila pilih lokasi pada peta.",
      "event_map_address_error": "Tidak dapat mendapatkan alamat untuk lokasi tersebut.",
      "event_map_confirm_button": "Sahkan Lokasi",
      "event_section_upcoming": "Aktiviti Akan Datang",
      "event_section_others": "Lain-lain",
      "submit": "Hantar",

      "eventDetail_title": "Butiran Acara",
      "eventDetail_points_label": "Mata untuk Diperoleh",
      "eventDetail_starts_on_label": "Bermula Pada",
      "eventDetail_ends_on_label": "Berakhir Pada",
      "eventDetail_location_label": "Lokasi",
      "eventDetail_organiser_label": "Penganjur",
      "eventDetail_contact_label": "Hubungi",
      "eventDetail_generate_qr_button": "Jana Kod QR",
      "eventDetail_qr_dialog_title": "Kod QR Acara",
      "eventDetail_close_button": "Tutup",
      "eventDetail_code_not_available": "Kod kehadiran tidak tersedia untuk acara ini.",
      "eventDetail_no_name": "Tiada Nama",
      "eventDetail_unknown": "Tidak diketahui",
      "eventDetail_not_applicable": "T/B",
      "eventDetail_no_location": "Tiada lokasi disediakan",

      "eventReview_success_title": "Anda telah berjaya mencipta acara!",
      "eventReview_success_subtitle": "Ia akan dipaparkan di halaman acara.",
      "eventReview_ok_button": "OK",

      "pickupItem_page_title": "Sahkan Kod Pengambilan Di Sini",
      "pickupItem_page_subtitle": "Imbas QR atau masukkan kod untuk memulakan pengesahan",
      "pickupItem_code_field_label": "Masukkan Kod Pengambilan atau Imbas QR",
      "pickupItem_code_field_hint": "Masukkan kod secara manual",
      "pickupItem_scan_qr_tooltip": "Imbas Kod QR",
      "pickupItem_verify_button": "Sahkan Identiti Asnaf",
      "pickupItem_reward_redeemed_label": "Ganjaran Ditebus",
      "pickupItem_asnaf_name_label": "Nama Asnaf",
      "pickupItem_asnaf_number_label": "Nombor Asnaf",
      "pickupItem_submit_button": "Sahkan & Hantar Pengambilan",
      "pickupItem_error_scan": "Ralat membuka pengimbas QR: ",
      "pickupItem_error_no_code": "Sila masukkan atau imbas kod pengambilan.",
      "pickupItem_error_not_found": "Kod pengambilan tidak ditemui.",
      "pickupItem_error_already_picked_up": "Pesanan ini telah pun diambil.",
      "pickupItem_error_not_processed": "Pesanan ini belum diproses oleh admin.",
      "pickupItem_error_no_ekyc": "Foto eKYC Asnaf tidak ditemui.",
      "pickupItem_error_validation_failed": "Pengesahan wajah gagal atau ditolak oleh staf.",
      "pickupItem_error_generic": "Berlaku ralat: ",
      "pickupItem_error_verify_first": "Sila sahkan identiti Asnaf terlebih dahulu.",
      "pickupItem_error_submit_failed": "Gagal menghantar pengambilan: ",
      "pickupItem_success_validation": "Pengesahan berjaya. Butiran dimuatkan.",

      "orderProcessed_title": "Proses Pesanan",
      "orderProcessed_subtitle": "Proses pesanan daripada Asnaf.",
      "orderProcessed_search_hint": "Cari Asnaf",
      "orderProcessed_filter_all": "Semua",
      "orderProcessed_filter_pending": "Menunggu",
      "orderProcessed_filter_approved": "Diluluskan",
      "orderProcessed_filter_rejected": "Ditolak",
      "orderProcessed_sort_date": "Tarikh",
      "orderProcessed_sort_name": "Nama",
      "orderProcessed_sort_status": "Status",
      "orderProcessed_no_applications": "Tiada permohonan ditemui",
      "orderProcessed_status_approve": "Lulus",
      "orderProcessed_status_pending": "Menunggu",
      "orderProcessed_unknown_user": "Tidak diketahui",
      "orderProcessed_no_code": "Tiada Kod",

      "stockItem_package_kasih": "Pakej Kasih",
      "stockItem_package_hamper": "Pakej Hamper",
      "stockItem_loading_dialog": "Menghantar Pakej...",
      "stockItem_warning_title_validation": "Ralat Pengesahan",
      "stockItem_warning_title_failed": "Pengesahan Gagal",
      "stockItem_warning_title_error": "Berlaku Ralat",
      "stockItem_warning_title_success": "Berjaya",
      "stockItem_ok_button": "OK",
      "stockItem_edit_package_name_title": "Sunting Nama Pakej",
      "stockItem_edit_package_name_hint": "Masukkan nama pakej baharu",
      "stockItem_cancel_button": "Batal",
      "stockItem_update_button": "Kemas kini",
      "stockItem_add_kasih_title": "Tambah Pakej Kasih",
      "stockItem_item_name_label": "Nama Barangan",
      "stockItem_search_hint": "Taip untuk mencari barangan...",
      "stockItem_select_item_warning": "Sila pilih barangan sebelum menghantar.",
      "stockItem_create_package_error": "Ralat mencipta pakej: ",
      "stockItem_submit_package_button": "Hantar Pakej",
      "stockItem_add_hamper_title": "Tambah Pakej Hamper",
      "stockItem_package_name_label": "Nama Pakej",
      "stockItem_hamper_name_hint": "cth., Hamper Raya Aidilfitri",
      "stockItem_voucher_value_label": "Nilai Baucar",
      "stockItem_items_label": "Barangan",
      "stockItem_hamper_name_warning": "Sila masukkan nama pakej.",
      "stockItem_add_item_warning": "Sila tambah sekurang-kurangnya satu barangan ke dalam hamper.",
      "stockItem_price_low_warning": "Harga terlalu rendah (RM @price). Perlu tambah sekurang-kurangnya RM @diff lagi.",
      "stockItem_price_high_warning": "Harga barangan terlalu tinggi (RM @price). Perlu kurangkan barangan sekurang-kurangnya RM @diff.",
      "stockItem_submit_hamper_button": "Hantar Hamper",
      "stockItem_kasih_list_title": "Pakej Kasih Tersedia",
      "stockItem_no_packages_available": "Tiada pakej tersedia",
      "stockItem_unnamed_package": "Pakej Tanpa Nama",
      "stockItem_no_category": "Tiada Kategori",
      "stockItem_package_deleted": "\"@title\" telah dipadamkan.",
      "stockItem_category_label": "Kategori: @category",
      "stockItem_price_label": "Harga: RM @price",
      "stockItem_hamper_list_title": "Pakej Hamper Tersedia",
      "stockItem_no_hampers_available": "Tiada hamper tersedia",
      "stockItem_unnamed_hamper": "Hamper Tanpa Nama",
      "stockItem_voucher_value_display": "Nilai Baucar: RM @value",

      "process_order_title": "Proses Pesanan",
      "update_order_no_data": "Tiada data ditemui untuk pesanan ini",
      "update_order_pickup_code_label": "Kod Pengambilan",
      "update_order_application_code": "Kod Permohonan",
      "update_order_value_redeemed": "Nilai Ditebus",
      "update_order_items_redeemed": "Barangan Ditebus",
      "update_order_no_items": "Tiada barangan untuk dipaparkan",
      "update_order_prompt": "Adakah anda telah selesai memproses pesanan?",
      "update_order_dropdown_no": "Tidak",
      "update_order_dropdown_yes": "Ya",
      "submit_button_text": "Hantar",
      "update_order_select_yes_prompt": "Sila pilih 'Ya' untuk meneruskan.",
      "update_order_success_message": "Status pesanan berjaya dikemas kini.",
      "update_order_failure_message": "Gagal mengemas kini status pesanan: @error",

      "verifyApp_title": "Sahkan Permohonan",
      "verifyApp_tab_all": "Semua",
      "verifyApp_tab_pending": "Menunggu",
      "verifyApp_tab_verified": "Disahkan",
      "verifyApp_tab_rejected": "Ditolak",
      "verifyApp_search_hint": "Cari Asnaf...",
      "verifyApp_sort_date": "Tarikh",
      "verifyApp_sort_name": "Nama",
      "verifyApp_sort_status": "Status",
      "verifyApp_error_generic": "Ralat: @error",
      "verifyApp_no_apps_found": "Tiada permohonan ditemui",
      "verifyApp_no_apps_in_category": "Tiada permohonan dalam kategori ini",
      "verifyApp_search_no_match": " sepadan dengan carian anda.",
      "verifyApp_unknown_user": "Tidak diketahui",
      "verifyApp_no_date": "Tiada tarikh diberikan",
      "verifyApp_no_code": "Tiada Kod",
      "verifyApp_submitted_by": "Dihantar oleh: @name",
      "verifyApp_status_approve": "Lulus",
      "verifyApp_status_pending": "Menunggu",
      "verifyApp_status_reject": "Tolak",

      "screening_title": "Menyaring Pemohon",
      "screening_error_generic": "Ralat: @error",
      "screening_no_data": "Tiada data ditemui untuk pemohon ini.",
      "screening_update_success": "Status permohonan berjaya dikemas kini!",
      "screening_nric_label": "NRIC",
      "screening_mobile_label": "Telefon Bimbit",
      "screening_email_label": "E-mel",
      "screening_address_label": "Alamat",
      "screening_residency_label": "Pemastautin",
      "screening_employment_label": "Pekerjaan",
      "screening_occupation_label": "Pekerjaan",
      "screening_income_label": "Pendapatan",
      "screening_asnaf_in_label": "Asnaf Di",
      "screening_justification_label": "Justifikasi",
      "screening_documents_title": "Dokumen yang Dimuat Naik",
      "screening_doc_proof_address": "Bukti Alamat",
      "screening_doc_proof_income": "Bukti Pendapatan",
      "screening_doc_not_provided": "Tidak Disediakan",
      "screening_viewing_doc": "Melihat: @file",
      "screening_update_status_title": "Kemas Kini Status",
      "screening_reason_title": "Sebab / Catatan",
      "screening_reason_hint": "Masukkan sebab kemas kini status (pilihan)...",
      "screening_submit_button": "Hantar Status",
      "screening_unknown_staff": "Staf Tidak Diketahui",

      "issueReward_title": "Beri Ganjaran",
      "issueReward_tab_all": "Semua",
      "issueReward_tab_pending": "Menunggu",
      "issueReward_tab_issued": "Diberi",
      "issueReward_tab_redeemed": "Ditebus",
      "issueReward_search_hint": "Cari ikut nama atau kod...",
      "issueReward_sort_date": "Tarikh",
      "issueReward_sort_name": "Nama",
      "issueReward_sort_status": "Status",
      "issueReward_error_generic": "Ralat: @error",
      "issueReward_no_apps_found": "Tiada permohonan ditemui",
      "issueReward_no_rewards_in_category": "Tiada ganjaran dalam kategori ini",
      "issueReward_search_no_match": " sepadan dengan carian anda.",
      "issueReward_unknown_user": "Tidak diketahui",
      "issueReward_no_date": "Tiada tarikh",
      "issueReward_not_applicable": "T/B",

      "voucherIssuance_title": "Pengeluaran Baucar",
      "voucherIssuance_app_not_found": "Permohonan tidak ditemui",
      "voucherIssuance_nric_label": "NRIC",
      "voucherIssuance_mobile_label": "Telefon Bimbit",
      "voucherIssuance_employment_label": "Status Pekerjaan",
      "voucherIssuance_income_label": "Pendapatan",
      "voucherIssuance_address_label": "Alamat",
      "voucherIssuance_justification_label": "Justifikasi",
      "voucherIssuance_submitted_by_staff": "Dihantar oleh Staf: @name",
      "voucherIssuance_submitted_by_user": "Dihantar oleh: @name",
      "voucherIssuance_reward_amount_label": "Jumlah Ganjaran",
      "voucherIssuance_aid_recurrence_label": "Bantuan Berulang",
      "voucherIssuance_recurring_switch_label": "Beri Bantuan Berulang",
      "voucherIssuance_recurrence_period_label": "Tempoh Berulang",
      "voucherIssuance_period_2_weeks": "2 Minggu",
      "voucherIssuance_period_1_month": "1 Bulan",
      "voucherIssuance_period_3_months": "3 Bulan",
      "voucherIssuance_period_6_months": "6 Bulan",
      "voucherIssuance_period_9_months": "9 Bulan",
      "voucherIssuance_period_1_year": "1 Tahun",
      "voucherIssuance_submit_button": "Berikan Ganjaran",
      "voucherIssuance_update_success": "Butiran ganjaran berjaya dikemas kini!",
      "voucherIssuance_update_fail": "Gagal mengemas kini butiran ganjaran: @error",
      "voucherIssuance_data_load_error": "Ralat memuatkan data awal: @error",

      "manageStaffs_title": "Urus Staf",
      "manageStaffs_subtitle": "Jejaki pengguna yang telah anda daftar atau urus.",
      "manageStaffs_search_hint": "Cari Pengguna",
      "manageStaffs_filter_button": "Tapis",
      "manageStaffs_role_admin": "Admin",
      "manageStaffs_role_staff": "Staf",
      "manageStaffs_role_asnaf": "Asnaf",
      "manageStaffs_sort_date": "Tarikh",
      "manageStaffs_sort_name": "Nama",
      "manageStaffs_error_generic": "Ralat: @error",
      "manageStaffs_no_users_found": "Tiada pengguna ditemui.",
      "manageStaffs_unknown_user": "Tidak diketahui",
      "manageStaffs_no_email": "Tiada E-mel",

      "staffDetails_title": "Urus Pengguna",
      "staffDetails_no_data": "Tiada data ditemui untuk pengguna ini.",
      "staffDetails_update_success": "Peranan pengguna berjaya dikemas kini!",
      "staffDetails_update_error": "Ralat mengemas kini peranan: @error",
      "staffDetails_label_fullName": "Nama Penuh",
      "staffDetails_label_nric": "NRIC",
      "staffDetails_label_email": "E-mel",
      "staffDetails_label_phone": "Telefon",
      "staffDetails_label_address": "Alamat",
      "staffDetails_label_role": "Peranan",
      "staffDetails_label_account_created": "Akaun Dicipta",
      "staffDetails_label_last_login": "Log Masuk Terakhir",
      "staffDetails_label_ekyc_verified": "eKYC Disahkan",
      "staffDetails_role_admin": "Admin",
      "staffDetails_role_staff": "Staf",
      "staffDetails_role_asnaf": "Asnaf",
      "staffDetails_submit_button": "Hantar",
      "staffDetails_not_applicable": "Tidak",

      "viewReports_title": "Laporan Papan Pemuka",
      "viewReports_subtitle": "Wawasan boleh tindakan untuk keputusan strategik.",
      "viewReports_chart_no_data": "Tiada data tersedia untuk dipaparkan.",
      "viewReports_funnel_title": "Analisis Saluran Permohonan",
      "viewReports_funnel_total": "Jumlah",
      "viewReports_funnel_pending": "Menunggu",
      "viewReports_funnel_approved": "Diluluskan",
      "viewReports_funnel_rejected": "Ditolak",
      "viewReports_region_title": "Pemohon mengikut Wilayah",
      "viewReports_region_other": "Lain-lain",
      "viewReports_donations_title": "Analisis Derma Bulanan",
      "viewReports_redemption_title": "Populariti Penebusan",
      "viewReports_redemption_summary": "Ringkasan",
      "viewReports_redemption_kasih": "Kasih",
      "viewReports_redemption_hamper": "Hamper",
      "viewReports_kasih_detail_title": "10 Item Kasih Paling Banyak Ditebus",
      "viewReports_hamper_detail_title": "Hamper yang Ditebus",
      "viewReports_chatbot_title": "Pembantu BI",
      "viewReports_chatbot_hint": "Tanya mengenai data...",
      "viewReports_chatbot_error": "Maaf, saya tidak dapat memberikan respons.",
      "viewReports_chatbot_generic_error": "Ralat: @error"
    },
  };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]![key] ?? key;
  }

  String translateWithArgs(String key, Map<String, String> args) {
    String translation = _localizedStrings[locale.languageCode]![key] ?? key;
    args.forEach((key, value) {
      translation = translation.replaceAll('@$key', value);
    });
    return translation;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ms'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}