# CORRECTED netlify.toml
[build]
publish = "build/web"
command = "git clone https://github.com/flutter/flutter.git --depth 1 && ./flutter/bin/flutter --version && ./flutter/bin/flutter pub get && ./flutter/bin/flutter build web --release"