// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNowNseSXlWqdY6cjyWENK5f1bkoAVnmY',
    appId: '1:531192957050:web:9305e4a224c50ad39593c3',
    messagingSenderId: '531192957050',
    projectId: 'kita-tongtong',
    authDomain: 'kita-tongtong.firebaseapp.com',
    storageBucket: 'kita-tongtong.firebasestorage.app',
    measurementId: 'G-ZY0NJ4D714',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQMQbVyGy-ei8wr0Al7GBmNmCFM58ZOY',
    appId: '1:531192957050:android:61f91401a0a6098a9593c3',
    messagingSenderId: '531192957050',
    projectId: 'kita-tongtong',
    storageBucket: 'kita-tongtong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_0Gc5-ZQ8yGqXjwsn473o0DKBjggDJps',
    appId: '1:531192957050:ios:63bb97d597d43b1b9593c3',
    messagingSenderId: '531192957050',
    projectId: 'kita-tongtong',
    storageBucket: 'kita-tongtong.firebasestorage.app',
    androidClientId: '531192957050-u7jr4s7jd5l65pujh92eku7smva74n55.apps.googleusercontent.com',
    iosClientId: '531192957050-pkjqlprdc2lhvbb0rmd5oo31jp72q9kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );
}
